/* Direito Administrativo — Módulo 09: Serviços públicos — conceito, princípios, classificação, concessão e permissão (modo direto) */
window.MOD = window.MOD || {};
window.MOD.dadm09 = (function(){
"use strict";

var CARDS = [
  ["Conceito de serviço público","É <b>incumbência do Estado</b>, conforme previsão <b>expressa na Constituição Federal de 1988</b>, podendo ser prestado <b>diretamente pelo poder público</b> ou <b>sob o regime de concessão ou permissão</b>."],
  ["Quais normas regem este assunto, segundo o resumo","<b>Lei 8.987/95</b> — Lei das Concessões · <b>Lei 11.079/04</b> — licitações e contratos para a <b>Parceria Público-Privada (PPP)</b> · <b>Lei 11.107/05</b> — Lei dos <b>Consórcios Públicos</b> · <b>Decreto 6.170/07</b> — regula os <b>convênios</b>."],
  ["Conceito de concessão de serviço público","É a <b>delegação da prestação de serviço público</b> feita pelo <b>poder concedente</b> (<b>União, Estado, DF ou Município</b>) <b>mediante licitação</b>, na modalidade <b>concorrência ou diálogo competitivo</b>, à <b>pessoa jurídica</b> (ou <b>consórcio de empresas</b>) que demonstre capacidade para seu desempenho, <b>por sua conta e risco</b> e por <b>prazo determinado</b>."],
  ["Serviços propriamente ditos × serviços de utilidade pública","<b>Propriamente ditos:</b> a Administração presta <b>diretamente</b> à comunidade, <b>sem delegação a terceiros</b>, por reconhecer sua <b>essencialidade</b>. <b>De utilidade pública:</b> a Administração reconhece a <b>conveniência</b>, mas <b>não</b> sua necessidade e essencialidade, e por isso ou os presta diretamente ou os <b>delega</b> a terceiros (<b>concessionários e permissionários</b>)."],
  ["Delegação: natureza jurídica de concessão, permissão e autorização","<b>Concessão</b> → <b>contrato administrativo</b>. <b>Permissão</b> → <b>contrato administrativo</b>. <b>Autorização</b> → <b>ato administrativo</b>."],
  ["Delegação: qual interesse predomina em cada figura","<b>Concessão</b> → predomina o <b>interesse público</b>. <b>Permissão</b> → <b>interesse público e privado</b>. <b>Autorização</b> → predomina o <b>interesse privado</b>."],
  ["Delegação: como fica a licitação em cada figura","<b>Concessão</b> → licitação <b>obrigatória</b>, na <b>concorrência ou diálogo competitivo</b>. <b>Permissão</b> → licitação <b>obrigatória</b>, em <b>qualquer modalidade</b>. <b>Autorização</b> → <b>não há licitação</b>."],
  ["Delegação: o que pode ser revogado","<b>Concessão</b> → <b>não pode ser revogada</b>. <b>Permissão</b> → <b>pode ser revogada</b> (<b>título precário</b>). <b>Autorização</b> → <b>pode ser revogada</b> (<b>título precário</b>)."],
  ["Delegação: quem pode ser o contratado","<b>Concessão</b> → o contratado <b>só pode ser pessoa jurídica</b> (ou <b>consórcio de empresas</b>). <b>Permissão</b> e <b>autorização</b> → o contratado pode ser <b>pessoa física ou jurídica</b>."],
  ["Permissão de serviço público × permissão de uso de bem público","<b>Permissão de Serviço Público = CONTRATO administrativo.</b> <b>Permissão de Uso de Bem Público = ATO administrativo.</b>"],
  ["Quais são os princípios do serviço público","<b>Continuidade</b> · <b>Economicidade</b> · <b>Generalidade</b> · <b>Atualidade</b> · <b>Modicidade</b>. (Atalho para decorar a lista na ordem do resumo: <b>C-E-G-A-M</b>.)"],
  ["Princípio da continuidade","Também chamado de <b>princípio da permanência</b>. Impõe que o serviço público, <b>uma vez instituído</b>, seja prestado de forma <b>permanente</b>, <b>sem interrupção</b>."],
  ["Princípio da economicidade","É a união da <b>qualidade</b>, da <b>celeridade</b> e do <b>menor custo</b> na prestação do serviço ou no trato com os bens públicos."],
  ["Princípio da generalidade","É atinente aos aspectos da <b>universalidade</b> e da <b>isonomia</b>. A característica de ser <b>universal</b> garante que o serviço seja ofertado da forma <b>mais abrangente possível</b>."],
  ["Princípio da atualidade","Diz respeito à <b>modernidade</b> das <b>técnicas</b>, dos <b>equipamentos</b>, das <b>instalações</b> e à sua <b>conservação</b>, bem como à <b>melhoria e expansão</b> do serviço."],
  ["Princípio da modicidade","O <b>valor pago</b> pela prestação dos serviços deve ser estabelecido segundo padrões de <b>razoabilidade</b>, mediante <b>tarifas mais baixas possíveis</b> cobradas dos usuários, a fim de manter a prestação do serviço à <b>maior parte possível da coletividade</b>."],
  ["Serviços coletivos (UTI UNIVERSI)","São prestados a <b>grupamentos indeterminados</b> de indivíduos, que <b>não têm direito subjetivo próprio</b> para sua obtenção. Exemplos: <b>pavimentação de ruas</b>, <b>iluminação pública</b>, <b>implantação do serviço de abastecimento de água</b> e <b>implantação do serviço de prevenção de doenças</b>."],
  ["Serviços singulares (UTI SINGULI)","São prestados a <b>destinatários individualizados</b>; é <b>mensurável a utilização</b> por cada indivíduo, e estes <b>possuem direito subjetivo</b> para sua obtenção. Prestado o serviço a outro na <b>mesma situação jurídica</b>, o interessado pode pleitear que a prestação também o alcance — senão, violado estaria o princípio da <b>impessoalidade</b> (art. 37 da CF), cabendo a via <b>judicial</b>. Exemplos: <b>energia domiciliar</b>, <b>água domiciliar</b>, <b>uso de linha telefônica</b>."],
  ["Como se fixa a tarifa do serviço público concedido","Será fixada pelo <b>preço da proposta vencedora da licitação</b> e <b>preservada pelas regras de revisão</b> previstas na <b>lei</b>, no <b>edital</b> e no <b>contrato</b>. Os concessionários <b>não detêm a liberdade própria da iniciativa privada</b> para alterar o valor da tarifa cobrada dos usuários."],
  ["Revisão da tarifa: tributos e alteração unilateral","Os contratos <b>poderão prever mecanismos de revisão</b> das tarifas, para manter o <b>equilíbrio econômico-financeiro</b>. <b>Ressalvados os impostos sobre a renda</b>, a criação, alteração ou extinção de <b>quaisquer tributos ou encargos legais</b> após a apresentação da proposta, comprovado o impacto, <b>implicará a revisão da tarifa, para mais ou para menos</b>. Havendo <b>alteração unilateral</b> que afete o equilíbrio inicial, o poder concedente <b>deverá restabelecê-lo concomitantemente à alteração</b>."],
  ["Tarifas diferenciadas e serviço alternativo e gratuito","As tarifas <b>poderão ser diferenciadas</b> em função das <b>características técnicas</b> e dos <b>custos específicos</b> provenientes do atendimento a <b>distintos segmentos de usuários</b>. E <b>somente com previsão legal específica</b> a cobrança da tarifa poderá ser <b>condicionada à existência de serviço público alternativo e gratuito</b> para o usuário."],
  ["Receitas alternativas","No atendimento às peculiaridades de cada serviço público, o <b>poder concedente</b> poderá prever, em favor da concessionária, <b>no edital de licitação</b>, a possibilidade de <b>outras fontes provenientes de receitas alternativas</b>, com vistas a favorecer a <b>modicidade das tarifas</b>."],
  ["As formas de extinção da concessão","<b>Advento do termo contratual</b> (atingimento do prazo previsto no contrato) · <b>encampação</b> (retomada do serviço pelo poder concedente) · <b>caducidade</b> (o contratado descumpre obrigações contratuais) · <b>rescisão</b> (o contratado entra na justiça para sair fora) · <b>anulação</b> (vício de legalidade) · <b>falência ou extinção</b> da empresa concessionária · <b>falecimento ou incapacidade do titular</b>, no caso de empresa individual."],
  ["Encampação — os três requisitos","É a <b>retomada do serviço pelo poder concedente durante o prazo da concessão</b>: por <b>motivo de interesse público</b> · mediante <b>lei autorizativa específica</b> · após <b>prévio pagamento da indenização</b>."],
  ["Caducidade da concessão — as três condições","Ocorre quando o contratado <b>descumpre obrigações contratuais</b>. Para declará-la: <b>1º)</b> a concessionária deverá ser <b>notificada para corrigir as falhas</b>; <b>2º)</b> não atendida a notificação, deverá ser instaurado <b>processo administrativo</b>, assegurados <b>ampla defesa + contraditório</b>; <b>3º)</b> a caducidade será declarada por <b>DECRETO</b> (<b>não é portaria</b>) do poder concedente."],
  ["Caducidade dos contratos × caducidade dos atos administrativos","<b>São coisas diferentes.</b> Caducidade dos <b>contratos</b> → o contratado <b>descumpre obrigações contratuais</b>. Caducidade dos <b>atos administrativos</b> → ocorre quando uma <b>norma jurídica posterior</b> torna <b>inviável a permanência da situação antes permitida</b> pelo ato."],
  ["Intervenção — finalidade e forma","No lugar de <b>decretar a caducidade</b>, o poder concedente pode promover a <b>intervenção</b>. A finalidade é <b>assegurar a adequação na prestação do serviço</b> e o <b>fiel cumprimento das normas contratuais, regulamentares e legais</b>. Far-se-á por <b>decreto</b> do poder concedente, que conterá a <b>designação do interventor</b>, o <b>prazo</b> da intervenção e os <b>objetivos e limites</b> da medida."],
  ["A intervenção é ato punitivo?","<b>Não.</b> Por isso <b>não há exigência de ampla defesa e contraditório prévios</b>. Porém, <b>uma vez decretado o ato interventivo, fica assegurado o direito de ampla defesa</b>."],
  ["Os prazos da intervenção","Declarada a intervenção, o poder concedente deverá, no prazo de <b>trinta dias</b>, <b>instaurar procedimento administrativo</b> para comprovar as causas determinantes da medida e apurar responsabilidades, assegurado o direito de ampla defesa. Esse procedimento deverá ser <b>concluído no prazo de até cento e oitenta dias</b>, sob pena de <b>considerar-se inválida a intervenção</b>."],
  ["Nulidade da intervenção","Se ficar comprovado que a intervenção <b>não observou os pressupostos legais e regulamentares</b>, será declarada sua <b>nulidade</b>, devendo o serviço ser <b>imediatamente devolvido à concessionária</b>, <b>sem prejuízo de seu direito à indenização</b>."],
  ["Concessão comum","É a delegação da prestação do serviço feita pelo <b>poder concedente</b> (U, E, DF, M) à <b>pessoa jurídica</b>; submete-se à <b>Lei 8.987/95</b>. Subdivide-se em <b>concessões simples</b> (o delegatário é remunerado <b>apenas pelas tarifas pagas pelos usuários</b>) e <b>concessões precedidas de obra</b> (o particular <b>realiza a obra às suas expensas</b> e é remunerado <b>posteriormente pela exploração do serviço decorrente da obra</b>)."],
  ["Concessão especial (PPP)","São as <b>Parcerias Público-Privadas</b>; submete-se à <b>Lei 11.079/04</b>. Pode ser <b>patrocinada</b> (<b>contraprestação do Estado + tarifa do usuário</b>) ou <b>administrativa</b> (<b>remuneração integral do Estado</b>, sendo a Administração <b>usuária direta ou indireta</b>). <b>Sempre haverá contraprestação pecuniária do Poder Público</b> ao parceiro privado; se o contrato <b>não prevê</b> essa contraprestação, <b>não será PPP, e sim concessão comum</b>."],
  ["Prazos: concessão comum × PPP","<b>Concessão comum (Lei 8.987/95):</b> a lei <b>não estabelece prazo máximo</b> para a vigência dos contratos de concessão de serviços públicos. <b>Concessão especial — PPP (Lei 11.079/04):</b> prazo <b>mínimo de 5</b> e <b>máximo de 35 anos</b> (<b>incluindo eventual prorrogação</b>)."],
  ["Arbitragem e os poderes dos financiadores","Nos contratos de concessão é permitida a previsão de <b>mecanismos privados não previstos nas normas gerais sobre licitações e contratos</b> — exemplo: <b>arbitragem</b>. O poder concedente poderá autorizar que os <b>financiadores</b> da concessionária <b>assumam temporariamente o controle da administração</b>, <b>indiquem membros dos conselhos de administração e fiscal</b> e <b>exerçam poder de veto</b> de proposta submetida à votação dos acionistas ou quotistas. Essa administração visa <b>promover a reestruturação financeira</b> e <b>assegurar a continuidade da prestação dos serviços</b>."],
  ["As duas pegadinhas das PPP","<b>1)</b> Não é o governo federal que concentra a maior parte das PPP no Brasil — <b>são os governos estaduais e municipais</b>. <b>2)</b> Não existe parceria público-privada <b>sem contraprestação pecuniária do parceiro público</b>: sem ela, o que se tem é <b>concessão comum</b>, em que a contraprestação vem das <b>tarifas pagas pelos usuários</b>."],
  ["Quando a interrupção NÃO caracteriza descontinuidade","Não se caracteriza descontinuidade a interrupção do serviço em <b>situação de emergência</b>, ou <b>após prévio aviso</b>: quando motivada por <b>razões de ordem técnica ou de segurança das instalações</b>; e quando por <b>inadimplemento do usuário</b>, <b>considerado o interesse da coletividade</b>."],
  ["Terceirização, subconcessão, transferência e responsabilidade","A concessionária <b>poderá contratar com terceiros</b> atividades <b>inerentes, acessórias ou complementares</b> ao serviço concedido, bem como a <b>implementação de projetos associados</b>. É admitida a <b>subconcessão</b>, nos termos do contrato, desde que <b>expressamente autorizada pelo poder concedente</b>. A <b>transferência de concessão ou de controle societário sem a prévia anuência</b> do poder concedente implica a <b>caducidade</b> (<b>não é anulação</b>). Incumbe à concessionária a <b>execução do serviço</b>, respondendo por <b>todos os prejuízos</b> causados ao poder concedente, aos usuários ou a terceiros, <b>sem que a fiscalização exclua ou atenue essa responsabilidade</b>."],
  ["Serviços econômicos, SV 41 do STF e Súmula 407 do STJ","<b>Serviços econômicos:</b> embora classificados como serviços públicos, <b>rendem ensejo a que o prestador aufira lucros</b>, com fisionomia similar às atividades <b>tipicamente empresariais</b>. <b>STF, Súmula Vinculante 41:</b> o <b>serviço de iluminação pública não pode ser remunerado mediante taxa</b> — fundamento: sua caracterização como serviço <b>UNIVERSAL</b>, pois as taxas só podem ser instituídas em razão do <b>poder de polícia</b> ou pela <b>utilização, efetiva ou potencial, de serviços públicos específicos e divisíveis</b>. <b>STJ, Súmula 407:</b> é <b>legítima a cobrança da tarifa de água</b> fixada de acordo com as <b>categorias de usuários</b> e as <b>faixas de consumo</b>."],
  ["Jurisprudência do corte de energia","<b>STJ, REsp 1.412.433:</b> é possível o <b>corte administrativo de energia elétrica</b>, <b>mediante prévio aviso</b> ao consumidor, pelo inadimplemento de <b>energia recuperada</b> correspondente ao período de <b>90 dias anterior à constatação da fraude</b> — é inadmissível o corte se a dívida por fraude no medidor for de período <b>anterior</b> a esses noventa dias. <b>STJ, REsp 1.755.345:</b> quando o devedor for <b>ente público</b>, <b>não</b> poderá haver corte <b>indiscriminado</b> em nome do interesse coletivo, sob pena de atingir serviços essenciais como <b>hospitais, centros de saúde, creches, escolas e iluminação pública</b>. Exemplo: município inadimplente há <b>120 dias</b> e corte em <b>hospital municipal</b> — a concessionária <b>agiu erradamente</b>."],
  ["Reversão","É a <b>transferência ao poder concedente</b> (U, E, DF, M) dos <b>bens do concessionário</b>, <b>afetados ao serviço público e necessários à sua continuidade</b>, <b>ao término do contrato</b> de concessão. Extinta a concessão, <b>retornam ao poder concedente todos os bens reversíveis, direitos e privilégios</b> transferidos ao concessionário. No <b>advento do termo contratual</b>, a reversão far-se-á com a <b>indenização das parcelas dos investimentos vinculados a bens reversíveis ainda não amortizados ou depreciados</b>; mas, se o bem <b>não era exigido contratualmente nem fora utilizado</b> na prestação do serviço, <b>não há ressarcimento</b>."]
];

var QS = [
  ["O serviço público é incumbência do Estado, conforme previsão expressa na Constituição Federal de 1988, podendo ser prestado diretamente pelo poder público ou sob o regime de concessão ou permissão.","C","CEBRASPE","Abertura do resumo."],
  ["Incumbe ao Poder Público, na forma do art. 175 da Constituição Federal, a prestação de serviços públicos, diretamente ou sob regime de concessão ou permissão, sempre por meio de licitação.","C","CF, art. 175","O resumo diz o conteúdo, mas não cita o número do artigo."],
  ["Serviços públicos propriamente ditos são aqueles em que a Administração reconhece a conveniência, mas não a necessidade e a essencialidade, podendo delegá-los a concessionários e permissionários.","E","FCC","Essa é a definição dos serviços <b>de utilidade pública</b>."],
  ["Os serviços de utilidade pública podem ser prestados diretamente pela Administração à sociedade ou delegados para execução por concessionários e permissionários.","C","FGV","Quadro de classificação dos serviços públicos."],
  ["Os serviços públicos propriamente ditos são prestados diretamente pela Administração à comunidade, sem delegação a terceiros, por reconhecer sua essencialidade.","C","VUNESP","Definição literal do quadro."],
  ["O princípio da continuidade, também chamado de princípio da permanência, impõe que o serviço público, uma vez instituído, seja prestado de forma permanente, sem interrupção.","C","AOCP","Conceito do resumo."],
  ["O princípio da generalidade diz respeito à modernidade das técnicas, dos equipamentos, das instalações e à sua conservação, bem como à melhoria e expansão do serviço.","E","IBFC","Essa é a <b>atualidade</b>; generalidade é universalidade e isonomia."],
  ["O princípio da atualidade é atinente aos aspectos da universalidade e da isonomia, garantindo que o serviço seja ofertado da forma mais abrangente possível.","E","FUNDATEC","Essa é a <b>generalidade</b>; atualidade é modernidade de técnicas e equipamentos."],
  ["Pelo princípio da modicidade, o valor pago pela prestação dos serviços deve ser estabelecido segundo padrões de razoabilidade, mediante tarifas mais baixas possíveis cobradas dos usuários.","C","CEBRASPE","Conceito do resumo."],
  ["O princípio da economicidade é a união da qualidade, da celeridade e do menor custo na prestação do serviço ou no trato com os bens públicos.","C","FCC","Conceito do resumo."],
  ["A concessão e a permissão de serviço público têm natureza de contrato administrativo, enquanto a autorização é ato administrativo.","C","FGV","Primeira linha do quadro da delegação."],
  ["Na concessão de serviço público predomina o interesse privado, enquanto na autorização predomina o interesse público.","E","VUNESP","Inverteu: na concessão predomina o <b>público</b>; na autorização, o <b>privado</b>."],
  ["A concessão de serviço público não pode ser revogada, ao contrário da permissão e da autorização, que constituem títulos precários.","C","AOCP","Quadro da delegação do serviço público."],
  ["Na concessão de serviço público, o contratado pode ser pessoa física ou jurídica; já na permissão e na autorização, somente pessoa jurídica.","E","IBFC","Inverteu a última linha do quadro da delegação."],
  ["A permissão de uso de bem público é contrato administrativo, e a permissão de serviço público é ato administrativo.","E","FUNDATEC","Inverteu a OBS do resumo: serviço público é <b>contrato</b>; uso de bem público é <b>ato</b>."],
  ["Serviços coletivos, ou uti universi, são aqueles prestados a grupamentos indeterminados de indivíduos, que não têm direito subjetivo próprio para sua obtenção.","C","CEBRASPE","Conceito do resumo."],
  ["A pavimentação de ruas e a iluminação pública são exemplos de serviços singulares, ou uti singuli.","E","FCC","São exemplos de serviços <b>coletivos (uti universi)</b>."],
  ["Nos serviços singulares, ou uti singuli, é mensurável a utilização por cada um dos indivíduos, que possuem direito subjetivo para sua obtenção, como na energia domiciliar.","C","FGV","Conceito e exemplo do resumo."],
  ["A concessão de serviço público é a delegação da prestação de serviço público feita pelo poder concedente mediante licitação, por sua conta e risco e por prazo indeterminado.","E","VUNESP","O prazo é <b>determinado</b>."],
  ["A concessão de serviço público exige licitação na modalidade concorrência ou diálogo competitivo, enquanto na permissão a licitação é obrigatória em qualquer modalidade.","C","AOCP","Quadro da delegação."],
  ["Somente a União pode figurar como poder concedente na concessão de serviço público.","E","IBFC","Poder concedente é a <b>União, o Estado, o DF ou o Município</b>."],
  ["A tarifa do serviço público concedido será fixada pelo preço da proposta vencedora da licitação e preservada pelas regras de revisão previstas na lei, no edital e no contrato.","C","FUNDATEC","Abertura da política tarifária."],
  ["Os concessionários de serviço público detêm a liberdade própria da iniciativa privada para alterar o valor da tarifa cobrada dos usuários.","E","CEBRASPE","O resumo diz o contrário: a tarifa se submete à lei, ao edital e ao contrato."],
  ["Ressalvados os impostos sobre a renda, a criação, alteração ou extinção de quaisquer tributos ou encargos legais, após a apresentação da proposta, quando comprovado seu impacto, implicará a revisão da tarifa, para mais ou para menos.","C","FGV","Observação 02 da política tarifária."],
  ["As tarifas não poderão ser diferenciadas em função das características técnicas e dos custos específicos provenientes do atendimento aos distintos segmentos de usuários.","E","VUNESP","Poderão, sim, ser diferenciadas — observação 04."],
  ["É vedado ao poder concedente prever, em favor da concessionária, no edital de licitação, a possibilidade de outras fontes provenientes de receitas alternativas.","E","AOCP","A observação 06 permite essas receitas, para favorecer a modicidade das tarifas."],
  ["A cobrança da tarifa do serviço público concedido pode ser condicionada à existência de serviço público alternativo e gratuito para o usuário, ainda que sem previsão legal específica.","E","IBFC","Só com <b>previsão legal específica</b>."],
  ["A encampação é a retomada do serviço pelo poder concedente durante o prazo da concessão, por motivo de interesse público, mediante lei autorizativa específica e após prévio pagamento da indenização.","C","Lei 8.987/95","Observação 01 das formas de extinção."],
  ["A caducidade da concessão consiste na retomada do serviço pelo poder concedente por motivo de interesse público, mediante lei autorizativa específica.","E","FUNDATEC","Essa é a <b>encampação</b>; a caducidade decorre do descumprimento de obrigações contratuais."],
  ["A caducidade da concessão será declarada por portaria do poder concedente, após processo administrativo em que se assegure ampla defesa e contraditório.","E","CEBRASPE","É por <b>decreto</b> — o resumo anota expressamente \"não é portaria\"."],
  ["Antes da declaração de caducidade, a concessionária deverá ser notificada para corrigir as falhas e, não atendida a notificação, será instaurado processo administrativo com ampla defesa e contraditório.","C","FCC","1º e 2º passos das condições da caducidade."],
  ["São formas de extinção da concessão o advento do termo contratual, a encampação, a caducidade, a rescisão, a anulação, a falência ou extinção da empresa concessionária e o falecimento ou incapacidade do titular, no caso de empresa individual.","C","FGV","Lista completa do resumo."],
  ["Caducidade dos contratos e caducidade dos atos administrativos são institutos equivalentes.","E","VUNESP","O resumo destaca: <b>caducidade dos contratos diferente de caducidade dos atos administrativos</b>."],
  ["No lugar de decretar a caducidade, o poder concedente pode promover a intervenção, que se fará por decreto contendo a designação do interventor, o prazo da intervenção e os objetivos e limites da medida.","C","AOCP","Conceito e observação 02 da intervenção."],
  ["A intervenção é ato punitivo e, por isso, exige ampla defesa e contraditório prévios.","E","IBFC","<b>Não é ato punitivo</b>; a ampla defesa é assegurada após o decreto interventivo."],
  ["Declarada a intervenção, o poder concedente deverá, no prazo de trinta dias, instaurar procedimento administrativo, que deverá ser concluído no prazo de até cento e oitenta dias, sob pena de considerar-se inválida a intervenção.","C","FUNDATEC","Observação 03 da intervenção."],
  ["Declarada a intervenção, o procedimento administrativo deve ser instaurado no prazo de sessenta dias e concluído em até cento e vinte dias.","E","CEBRASPE","Os prazos são <b>30</b> e <b>180</b> dias."],
  ["Comprovado que a intervenção não observou os pressupostos legais e regulamentares, será declarada sua nulidade, devendo o serviço ser imediatamente devolvido à concessionária, sem prejuízo de seu direito à indenização.","C","FCC","Observação 04 da intervenção."],
  ["A concessão comum submete-se à Lei 8.987/95 e subdivide-se em concessões simples ou concessões precedidas de obra.","C","FGV","Conceito de concessão comum."],
  ["Na concessão simples, o particular deve realizar a obra às suas expensas e será remunerado posteriormente pela exploração do serviço decorrente da obra.","E","VUNESP","Essa é a <b>concessão precedida de obra</b>; na simples só há tarifa dos usuários."],
  ["A concessão especial corresponde às parcerias público-privadas, submete-se à Lei 11.079/04 e pode ser patrocinada ou administrativa.","C","AOCP","Conceito de concessão especial."],
  ["Na concessão patrocinada a remuneração é integral do Estado, e na concessão administrativa há contraprestação do Estado somada à tarifa do usuário.","E","IBFC","Inverteu: patrocinada é contraprestação + tarifa; administrativa é remuneração integral do Estado."],
  ["Se o contrato não prevê contraprestação pecuniária do Poder Público ao parceiro privado, não haverá parceria público-privada, e sim concessão comum.","C","FUNDATEC","Fecho do quadro da concessão especial."],
  ["O governo federal concentra a maior parte das parcerias público-privadas no Brasil.","E","CEBRASPE","Questão-pegadinha: são os governos <b>estaduais e municipais</b>."],
  ["A Lei 8.987/95 não estabelece prazo máximo para a vigência dos contratos de concessão de serviços públicos, enquanto a Lei 11.079/04 fixa prazo mínimo de 5 e máximo de 35 anos, incluindo eventual prorrogação.","C","FCC","Tome Nota 11."],
  ["A reversão é a transferência ao poder concedente dos bens do concessionário afetados ao serviço público e necessários à sua continuidade, ao término do contrato de concessão.","C","FGV","Tome Nota 15."],
  ["Não se caracteriza como descontinuidade do serviço a sua interrupção em situação de emergência, ou, após prévio aviso, quando motivada por razões de ordem técnica ou de segurança das instalações, ou por inadimplemento do usuário, considerado o interesse da coletividade.","C","VUNESP","Tome Nota 01."],
  ["A transferência de concessão ou de controle societário da concessionária sem a prévia anuência do poder concedente implicará a anulação da concessão.","E","AOCP","Implica a <b>caducidade</b> — o resumo anota \"não é anulação\"."],
  ["O serviço de iluminação pública não pode ser remunerado mediante taxa, pois as taxas, nos termos do art. 145, II, da Constituição Federal, só podem ser instituídas em razão do exercício do poder de polícia ou pela utilização, efetiva ou potencial, de serviços públicos específicos e divisíveis.","C","Súmula Vinculante 41 do STF","O resumo traz as duas hipóteses, mas não cita o dispositivo constitucional."],
  ["É ilegítima a cobrança da tarifa de água fixada de acordo com as categorias de usuários e as faixas de consumo.","E","Súmula 407 do STJ","A súmula afirma o contrário: a cobrança é <b>legítima</b>."],
  ["É vedada a subconcessão nos contratos de concessão de serviço público, ainda que prevista no contrato e expressamente autorizada pelo poder concedente.","E","IBFC","O Tome Nota 13 <b>admite</b> a subconcessão nessas condições."],
  ["Concessionárias de serviços públicos podem terceirizar quaisquer de suas atividades, exceto as atividades-fim.","E","FUNDATEC","A ADC 57 do STF admite a terceirização <b>inclusive</b> das atividades-fim."]
];

function sl(h,b){return {h:h,b:b};}

var TEORIA = {
  V1:[
    sl("Serviço público: conceito, classificação, princípios e as três figuras de delegação",
      '<div class="box"><span class="bl">Onde este assunto mora</span>'+
      '<p>O resumo abre avisando que a relevância é <b>altíssima</b> e que o tópico abrange um conjunto de normas que o tornam gigantesco:</p>'+
      '<div class="chips"><span class="chip">Lei 8.987/95 — Concessões</span><span class="chip">Lei 11.079/04 — PPP</span><span class="chip">Lei 11.107/05 — Consórcios Públicos</span><span class="chip">Decreto 6.170/07 — Convênios</span></div>'+
      '<p>Por isso o material foi dividido em <b>duas partes</b>: a concessão especial (PPP) é detalhada no PDF seguinte.</p></div>'+
      '<div class="box"><span class="bl">Serviço público</span>'+
      '<p>É <b>incumbência do Estado</b>, conforme <b>previsão expressa na Constituição Federal de 1988</b>, podendo ser prestado <b>diretamente pelo poder público</b> ou <b>sob o regime de concessão ou permissão</b>.</p>'+
      '<p><b>Concessão de serviço público</b> é a <b>delegação da prestação de serviço público</b> feita pelo <b>poder concedente</b> (<b>União, Estado, DF ou Município</b>) <b>mediante licitação</b>, na modalidade <b>concorrência ou diálogo competitivo</b>, à <b>pessoa jurídica</b> (ou <b>consórcio de empresas</b>) que demonstre capacidade para seu desempenho, <b>por sua conta e risco</b> e por <b>prazo determinado</b>.</p></div>'+
      '<div class="box"><span class="bl">Classificação: propriamente ditos × de utilidade pública</span>'+
      '<div class="tree"><div class="leaf"><b>PROPRIAMENTE DITOS</b> — a Administração presta <b>diretamente</b> à comunidade, <b>sem delegação a terceiros</b>, por reconhecer sua <b>essencialidade</b>.</div>'+
      '<div class="leaf"><b>DE UTILIDADE PÚBLICA</b> — a Administração reconhece a <b>conveniência</b>, mas <b>não</b> sua <b>necessidade e essencialidade</b>, e por isso ou os presta diretamente à sociedade ou os <b>delega</b> para que sejam executados por terceiros (<b>concessionários e permissionários</b>).</div></div>'+
      '<p>A palavra que separa os dois é <b>essencialidade</b>: reconhecida, o serviço fica com a Administração; apenas <b>conveniente</b>, pode ser delegado.</p></div>'+
      '<div class="box"><span class="bl">Serviços coletivos × serviços singulares</span>'+
      '<div class="tree"><div class="leaf"><b>COLETIVOS (UTI UNIVERSI)</b> — prestados a <b>grupamentos indeterminados</b> de indivíduos, que <b>não têm direito subjetivo próprio</b> para sua obtenção. Ex.: <b>pavimentação de ruas</b>, <b>iluminação pública</b>, <b>implantação do serviço de abastecimento de água</b>, <b>implantação do serviço de prevenção de doenças</b>.</div>'+
      '<div class="leaf"><b>SINGULARES (UTI SINGULI)</b> — prestados a <b>destinatários individualizados</b>; é <b>mensurável a utilização</b> por cada indivíduo e estes <b>possuem direito subjetivo</b> para sua obtenção. Ex.: <b>energia domiciliar</b>, <b>água domiciliar</b>, <b>uso de linha telefônica</b>.</div></div>'+
      '<p>Nos <b>uti singuli</b>, se o serviço é prestado a outro na <b>mesma situação jurídica</b>, o interessado pode pleitear que a prestação também o alcance; do contrário, violado estaria o princípio da <b>impessoalidade</b> (art. 37 da CF) e o prejudicado pode recorrer à <b>via judicial</b>.</p></div>'+
      '<div class="box tip"><span class="bl">Os princípios do serviço público</span>'+
      '<p>Atalho para a lista do resumo, na ordem em que ele a apresenta: <b>C-E-G-A-M</b>.</p>'+
      '<ul><li><b>Continuidade</b> — também chamado de <b>permanência</b>: o serviço, <b>uma vez instituído</b>, deve ser prestado de forma <b>permanente</b>, <b>sem interrupção</b>.</li>'+
      '<li><b>Economicidade</b> — união da <b>qualidade</b>, da <b>celeridade</b> e do <b>menor custo</b> na prestação do serviço ou no trato com os bens públicos.</li>'+
      '<li><b>Generalidade</b> — atinente à <b>universalidade</b> e à <b>isonomia</b>; ser <b>universal</b> garante que o serviço seja ofertado da forma <b>mais abrangente possível</b>.</li>'+
      '<li><b>Atualidade</b> — <b>modernidade</b> das <b>técnicas</b>, dos <b>equipamentos</b>, das <b>instalações</b> e sua <b>conservação</b>, bem como a <b>melhoria e expansão</b> do serviço.</li>'+
      '<li><b>Modicidade</b> — o valor pago deve seguir padrões de <b>razoabilidade</b>, com as <b>tarifas mais baixas possíveis</b>, para manter o serviço à <b>maior parte possível da coletividade</b>.</li></ul>'+
      '<p>As duas trocas que a banca faz aqui são sempre as mesmas: <b>generalidade</b> (universalidade/isonomia) descrita como <b>atualidade</b> (modernidade de técnicas e equipamentos), e vice-versa.</p></div>'+
      '<div class="box"><span class="bl">Delegação do serviço público — o quadro inteiro</span>'+
      '<ul><li><b>Natureza:</b> concessão = <b>contrato administrativo</b> · permissão = <b>contrato administrativo</b> · autorização = <b>ato administrativo</b>.</li>'+
      '<li><b>Interesse:</b> concessão = predomina o <b>público</b> · permissão = <b>público e privado</b> · autorização = predomina o <b>privado</b>.</li>'+
      '<li><b>Licitação:</b> concessão = <b>obrigatória</b> (<b>concorrência ou diálogo competitivo</b>) · permissão = <b>obrigatória</b> (<b>qualquer modalidade</b>) · autorização = <b>não há licitação</b>.</li>'+
      '<li><b>Revogação:</b> concessão = <b>não pode ser revogada</b> · permissão e autorização = <b>podem ser revogadas</b> (<b>título precário</b>).</li>'+
      '<li><b>Contratado:</b> concessão = <b>só pessoa jurídica</b> (ou consórcio de empresas) · permissão e autorização = <b>pessoa física ou jurídica</b>.</li></ul></div>'+
      '<div class="box trap"><span class="bl">A OBS que a banca inverte</span>'+
      '<p><b>Permissão de Serviço Público = CONTRATO administrativo.</b></p>'+
      '<p><b>Permissão de Uso de Bem Público = ATO administrativo.</b></p>'+
      '<p class="mn"><em>Serviço, contrato. Bem, ato. Se a assertiva trocar a ordem, está errada.</em></p></div>')
  ],
  V2:[
    sl("Política tarifária, extinção da concessão e intervenção",
      '<div class="box"><span class="bl">Da política tarifária</span>'+
      '<p>A tarifa do serviço público concedido será fixada pelo <b>preço da proposta vencedora da licitação</b> e <b>preservada pelas regras de revisão</b> previstas na <b>lei</b>, no <b>edital</b> e no <b>contrato</b>.</p>'+
      '<p>Ou seja: os concessionários <b>não detêm a liberdade própria da iniciativa privada</b> para alterar o valor da tarifa cobrada dos usuários, já que ela se submete aos termos da <b>lei</b>, do <b>edital</b> e do <b>contrato</b>.</p></div>'+
      '<div class="box"><span class="bl">As seis observações da tarifa</span>'+
      '<ul><li><b>01</b> — os contratos <b>poderão prever mecanismos de revisão</b> das tarifas, para manter o <b>equilíbrio econômico-financeiro</b>.</li>'+
      '<li><b>02</b> — <b>ressalvados os impostos sobre a renda</b>, a <b>criação, alteração ou extinção de quaisquer tributos ou encargos legais</b> após a apresentação da proposta, comprovado o impacto, <b>implicará a revisão da tarifa, para mais ou para menos</b>.</li>'+
      '<li><b>03</b> — havendo <b>alteração unilateral</b> do contrato que afete o <b>equilíbrio inicial</b>, o poder concedente (U, E, DF, M) <b>deverá restabelecê-lo concomitantemente à alteração</b>.</li>'+
      '<li><b>04</b> — as tarifas <b>poderão ser diferenciadas</b> em função das <b>características técnicas</b> e dos <b>custos específicos</b> do atendimento a <b>distintos segmentos de usuários</b>.</li>'+
      '<li><b>05</b> — <b>havendo previsão legal específica</b>, a cobrança da tarifa poderá ser <b>condicionada à existência de serviço público alternativo e gratuito</b> para o usuário.</li>'+
      '<li><b>06</b> — o poder concedente poderá prever, em favor da concessionária, <b>no edital de licitação</b>, a possibilidade de <b>outras fontes provenientes de receitas alternativas</b>, para favorecer a <b>modicidade das tarifas</b>.</li></ul></div>'+
      '<div class="box"><span class="bl">Formas de extinção da concessão</span>'+
      '<ul><li><b>Advento do termo contratual</b> — atingimento do prazo previsto no contrato.</li>'+
      '<li><b>Encampação</b> — retomada do serviço pelo poder concedente.</li>'+
      '<li><b>Caducidade</b> — o contratado <b>descumpre obrigações contratuais</b>.</li>'+
      '<li><b>Rescisão</b> — o contratado <b>entra na justiça</b> para sair fora.</li>'+
      '<li><b>Anulação</b> — há <b>vício de legalidade</b>.</li>'+
      '<li><b>Falência ou extinção</b> da empresa concessionária.</li>'+
      '<li><b>Falecimento ou incapacidade do titular</b>, no caso de empresa individual.</li></ul></div>'+
      '<div class="box trap"><span class="bl">Encampação × caducidade — o par que decide a questão</span>'+
      '<p><b>ENCAMPAÇÃO</b> é a retomada do serviço pelo poder concedente <b>durante o prazo da concessão</b>: por <b>motivo de interesse público</b> · mediante <b>lei autorizativa específica</b> · após <b>prévio pagamento da indenização</b>.</p>'+
      '<p><b>CADUCIDADE</b> ocorre quando o contratado <b>descumpre obrigações contratuais</b>. Condições para declará-la: <b>1º)</b> a concessionária deve ser <b>notificada para corrigir as falhas</b>; <b>2º)</b> não atendida a notificação, instaura-se <b>processo administrativo</b>, com <b>ampla defesa + contraditório</b>; <b>3º)</b> a caducidade é declarada por <b>DECRETO</b> do poder concedente — <b>não é portaria</b>.</p>'+
      '<p><b>Caducidade dos contratos ≠ caducidade dos atos administrativos.</b> A caducidade de <b>ATOS</b> ocorre quando uma <b>norma jurídica posterior</b> torna <b>inviável a permanência da situação antes permitida</b> pelo ato.</p></div>'+
      '<div class="box"><span class="bl">As duas questões-exemplo do resumo</span>'+
      '<p><b>FGV — CM Aracaju 2021.</b> Município Alfa, em Sergipe, celebrou concessão com a sociedade empresária Gama para o serviço de <b>abastecimento de água potável</b>; no curso do contrato, por <b>motivo de interesse público</b> justificado, o prefeito deseja retomar o serviço. Gabarito: a retomada ocorre por <b>encampação</b>, <b>mediante lei autorizativa específica e após prévio pagamento da indenização</b> à concessionária.</p>'+
      '<p><b>FGV — TJ PR 2021.</b> A concessionária Alfa, do <b>transporte coletivo intramunicipal</b>, circulava com <b>ônibus sem ar-condicionado, pneus carecas e bancos rasgados</b>, sem portas acessíveis a pessoas com deficiência, e não observava rotas e horários; descumpriu cláusulas contratuais e normas legais, não cumpriu as penalidades e não atendeu à intimação para regularizar. Gabarito: <b>caducidade</b>, cuja declaração <b>por decreto do Prefeito</b> deve ser precedida da verificação da inadimplência em <b>processo administrativo</b>, assegurada a <b>ampla defesa</b>, <b>independentemente de indenização prévia</b>.</p></div>'+
      '<div class="box tip"><span class="bl">Da intervenção</span>'+
      '<p><b>No lugar de decretar a caducidade</b>, o poder concedente pode promover a <b>intervenção</b>, designando o <b>interventor</b>, o <b>prazo</b> da intervenção e os <b>objetivos</b> da medida. A finalidade é <b>assegurar a adequação na prestação do serviço</b> e o <b>fiel cumprimento das normas contratuais, regulamentares e legais</b> pertinentes.</p>'+
      '<ul><li><b>01</b> — a intervenção <b>não é ato punitivo</b> e, por isso, <b>não há exigência de ampla defesa e contraditório prévios</b>; porém, <b>uma vez decretado o ato interventivo, fica assegurado o direito de ampla defesa</b>.</li>'+
      '<li><b>02</b> — far-se-á por <b>decreto</b> do poder concedente, que conterá a <b>designação do interventor</b>, o <b>prazo</b> da intervenção e os <b>objetivos e limites</b> da medida.</li>'+
      '<li><b>03</b> — declarada a intervenção, o poder concedente deverá, no prazo de <b>trinta dias</b>, <b>instaurar procedimento administrativo</b> para comprovar as causas e apurar responsabilidades, assegurada a ampla defesa; esse procedimento deve ser <b>concluído em até cento e oitenta dias</b>, sob pena de <b>considerar-se inválida a intervenção</b>.</li>'+
      '<li><b>04</b> — comprovado que a intervenção <b>não observou os pressupostos legais e regulamentares</b>, será declarada sua <b>nulidade</b>, com <b>devolução imediata do serviço</b> à concessionária, <b>sem prejuízo de seu direito à indenização</b>.</li></ul>'+
      '<p><b>Questão-exemplo (FGV — OAB 2020):</b> o Município Beta concedeu o serviço de <b>veículos leves sobre trilhos</b> e verificou que a concessionária não cumpria adequadamente as obrigações do contrato. Gabarito: é possível a <b>intervenção</b>, para assegurar a adequada prestação, <b>por decreto do poder concedente</b>, com <b>designação do interventor, o prazo, os objetivos e os limites</b> da medida.</p>'+
      '<p class="mn"><em>30 dias para instaurar, 180 para concluir. Fora disso, a intervenção é inválida.</em></p></div>')
  ],
  V3:[
    sl("Concessão comum, concessão especial (PPP) e os conceitos que já caíram",
      '<div class="box"><span class="bl">Concessão comum</span>'+
      '<p>Delegação da prestação do serviço feita pelo <b>poder concedente</b> (U, E, DF, M) à <b>pessoa jurídica</b>; submete-se à <b>Lei 8.987/95</b>. Subdivide-se em:</p>'+
      '<div class="tree"><div class="leaf"><b>CONCESSÃO SIMPLES</b> — o particular delegatário é remunerado <b>apenas pelas tarifas pagas pelos usuários</b>.</div>'+
      '<div class="leaf"><b>CONCESSÃO PRECEDIDA DE OBRA</b> — o particular deve <b>realizar a obra às suas expensas</b> e será remunerado <b>posteriormente pela exploração do serviço decorrente da obra</b>.</div></div></div>'+
      '<div class="box"><span class="bl">Concessão especial — as PPP</span>'+
      '<p>São as <b>Parcerias Público-Privadas</b>; submetem-se à <b>Lei 11.079/04</b>.</p>'+
      '<div class="tree"><div class="leaf"><b>PATROCINADA</b> — <b>contraprestação do Estado + tarifa do usuário</b>.</div>'+
      '<div class="leaf"><b>ADMINISTRATIVA</b> — <b>remuneração integral do Estado</b>; aqui a Administração Pública é <b>usuária direta ou indireta</b>.</div></div>'+
      '<p><b>Sempre haverá uma contraprestação pecuniária do Poder Público</b> ao parceiro privado. Se o contrato <b>não prevê</b> essa contraprestação, <b>não será PPP, e sim concessão comum</b>.</p>'+
      '<p><b>Quadro comparativo:</b> na <b>concessão comum</b> o delegatário é remunerado <b>apenas pelas tarifas</b> pagas pelos usuários; na <b>concessão especial</b>, <b>sempre</b> há contraprestação pecuniária do Poder Público ao parceiro privado. O resumo avisa que a PPP será detalhada no próximo PDF.</p></div>'+
      '<div class="box trap"><span class="bl">As duas questões-pegadinha das PPP</span>'+
      '<p><b>CESPE — IPHAN 2018:</b> \"O governo federal concentra a maior parte das parcerias público-privadas no Brasil.\" <b>ERRADO</b> — <b>são os governos estaduais e municipais</b> que concentram a maior parte das PPP.</p>'+
      '<p><b>CESPE — CODEVASF 2021:</b> \"É permitida a constituição de parceria público-privada para a exploração de uma concessão comum, desde que essa parceria não envolva uma contraprestação pecuniária do parceiro público.\" <b>ERRADO</b> — sem contraprestação pecuniária do parceiro público <b>não há parceria (concessão especial)</b>, e sim <b>concessão comum</b>, em que a contraprestação vem das <b>tarifas pagas pelos usuários</b>.</p></div>'+
      '<div class="box"><span class="bl">Prazos, arbitragem e financiadores</span>'+
      '<p><b>Prazos:</b> na <b>concessão comum (Lei 8.987/95)</b> a lei <b>não estabelece prazo máximo</b> de vigência; na <b>concessão especial — PPP (Lei 11.079/04)</b> o prazo é de <b>mínimo 5</b> e <b>máximo 35 anos</b>, <b>incluindo eventual prorrogação</b>.</p>'+
      '<p><b>Arbitragem:</b> nos contratos de concessão é permitida a previsão de <b>mecanismos privados não previstos nas normas gerais sobre licitações e contratos</b> — exemplo: a <b>arbitragem</b>, em que as partes escolhem uma pessoa, física ou jurídica, para solucionar a lide, deixando de lado a prestação jurisdicional estatal.</p>'+
      '<p><b>Financiadores:</b> o poder concedente poderá autorizar que os financiadores da concessionária <b>assumam temporariamente o controle da administração</b>, <b>indiquem membros dos conselhos de administração e fiscal</b> e <b>exerçam poder de veto</b> de proposta submetida à votação dos acionistas ou quotistas. Essa administração visa <b>promover a reestruturação financeira</b> da concessionária e <b>assegurar a continuidade da prestação dos serviços</b>.</p></div>'+
      '<div class="box"><span class="bl">Conceitos importantes — leitura de \"lei seca\"</span>'+
      '<ul><li><b>Interrupção que não é descontinuidade:</b> em <b>situação de emergência</b>, ou <b>após prévio aviso</b>, por <b>razões de ordem técnica ou de segurança das instalações</b>, ou por <b>inadimplemento do usuário</b>, considerado o <b>interesse da coletividade</b>.</li>'+
      '<li><b>Terceiros:</b> a concessionária poderá contratar com terceiros atividades <b>inerentes, acessórias ou complementares</b> ao serviço concedido e a <b>implementação de projetos associados</b>.</li>'+
      '<li><b>Subconcessão:</b> admitida nos termos do contrato, desde que <b>expressamente autorizada pelo poder concedente</b>.</li>'+
      '<li><b>Transferência sem anuência:</b> a transferência de concessão ou de <b>controle societário</b> sem a <b>prévia anuência</b> do poder concedente implica a <b>caducidade</b> — <b>não é anulação</b>.</li>'+
      '<li><b>Responsabilidade:</b> incumbe à concessionária a execução do serviço, respondendo por <b>todos os prejuízos</b> causados ao poder concedente, aos usuários ou a terceiros, <b>sem que a fiscalização exercida pelo órgão competente exclua ou atenue</b> essa responsabilidade.</li>'+
      '<li><b>Serviços econômicos:</b> embora classificados como serviços públicos, <b>rendem ensejo a que o prestador aufira lucros</b>, com fisionomia similar às atividades <b>tipicamente empresariais</b> (industrial e comercial).</li>'+
      '<li><b>Essencialidade:</b> a essencialidade de certos serviços públicos é prevista <b>tanto na Constituição Federal de 1988 quanto em leis ordinárias</b>.</li>'+
      '<li><b>Reversão:</b> transferência ao poder concedente dos <b>bens do concessionário afetados ao serviço</b> e necessários à sua continuidade, <b>ao término do contrato</b>. Extinta a concessão, retornam ao poder concedente <b>todos os bens reversíveis, direitos e privilégios</b>. No <b>advento do termo</b>, com <b>indenização das parcelas dos investimentos vinculados a bens reversíveis ainda não amortizados ou depreciados</b>; mas, se o bem <b>não era exigido contratualmente nem fora utilizado</b> na prestação, <b>não há ressarcimento</b>.</li></ul></div>'+
      '<div class="box tip"><span class="bl">Súmulas e julgados do resumo</span>'+
      '<ul><li><b>STF, Súmula Vinculante 41:</b> o <b>serviço de iluminação pública não pode ser remunerado mediante taxa</b>. O fundamento está na caracterização desse serviço como <b>UNIVERSAL</b>, já que as taxas só podem ser instituídas <b>em razão do exercício do poder de polícia</b> ou <b>pela utilização, efetiva ou potencial, de serviços públicos específicos e divisíveis</b>.</li>'+
      '<li><b>STJ, Súmula 407:</b> é <b>legítima a cobrança da tarifa de água</b> fixada de acordo com as <b>categorias de usuários</b> e as <b>faixas de consumo</b>.</li>'+
      '<li><b>STF, ADC 57 (03/10/2019):</b> concessionárias de serviços públicos podem <b>terceirizar quaisquer de suas atividades, inclusive suas atividades-fim</b>.</li>'+
      '<li><b>STJ, REsp 1.412.433:</b> é possível o <b>corte administrativo de energia elétrica</b>, <b>mediante prévio aviso</b>, pelo inadimplemento de <b>energia recuperada</b> do período de <b>90 dias anterior à constatação da fraude</b>. Logo, o corte é <b>inadmissível</b> se a dívida por fraude no medidor for de período <b>anterior</b> a esses noventa dias.</li>'+
      '<li><b>STJ, REsp 1.755.345:</b> sendo o devedor <b>ente público</b>, <b>não</b> cabe corte <b>indiscriminado</b> de energia em nome do interesse coletivo, sob pena de atingir serviços essenciais como <b>hospitais, centros de saúde, creches, escolas e iluminação pública</b>. No exemplo do resumo, o município estava inadimplente há <b>120 dias</b> e a concessionária cortou a energia de <b>prédio onde funciona hospital municipal</b>: <b>agiu erradamente</b>, pois a interrupção foi prejudicial ao <b>interesse da coletividade</b>, aplicando-se a <b>supremacia do interesse público sobre o privado</b>.</li></ul></div>')
  ]
};

var EX = {
S1:{t:"sort", instr:"Serviço coletivo (uti universi) ou singular (uti singuli)?",
  buckets:["Coletivo (uti universi)","Singular (uti singuli)"],
  items:[["Pavimentação de ruas",0],
         ["Iluminação pública",0],
         ["Implantação do serviço de abastecimento de água",0],
         ["Implantação do serviço de prevenção de doenças",0],
         ["Energia domiciliar",1],
         ["Água domiciliar",1],
         ["Uso de linha telefônica",1]],
  why:"Nos uti universi os destinatários são indeterminados e não há direito subjetivo próprio; nos uti singuli a utilização é mensurável e há direito subjetivo."},

S2:{t:"match", instr:"Correlacione cada princípio do serviço público à sua definição",
  pairs:[["Continuidade","Também chamado de permanência: o serviço, uma vez instituído, deve ser prestado sem interrupção"],
         ["Economicidade","União da qualidade, da celeridade e do menor custo na prestação do serviço"],
         ["Generalidade","Universalidade e isonomia: o serviço deve ser ofertado da forma mais abrangente possível"],
         ["Atualidade","Modernidade das técnicas, dos equipamentos e das instalações, e melhoria e expansão do serviço"],
         ["Modicidade","Tarifas mais baixas possíveis, segundo padrões de razoabilidade"]],
  why:"As trocas que a banca faz são sempre entre generalidade e atualidade."},

S3:{t:"gap", instr:"Complete a frase",
  before:"O princípio da continuidade também é chamado de princípio da ",
  after:", e impõe que o serviço público, uma vez instituído, seja prestado de forma permanente, sem interrupção.",
  options:["permanência","modicidade","generalidade"], answer:0,
  why:"Continuidade e permanência são o mesmo princípio no resumo."},

S4:{t:"sort", instr:"A característica é da concessão ou da autorização?",
  buckets:["Concessão","Autorização"],
  items:[["Contrato administrativo",0],
         ["Ato administrativo",1],
         ["Predomina o interesse público",0],
         ["Predomina o interesse privado",1],
         ["Licitação obrigatória, na concorrência ou no diálogo competitivo",0],
         ["Não há licitação",1],
         ["Não pode ser revogado",0],
         ["Pode ser revogado — título precário",1],
         ["O contratado só pode ser pessoa jurídica ou consórcio de empresas",0],
         ["O contratado pode ser pessoa física ou jurídica",1]],
  why:"A permissão fica no meio: contrato administrativo, interesse público e privado, licitação obrigatória em qualquer modalidade, revogável (título precário) e contratado pessoa física ou jurídica."},

S5:{t:"mc", instr:"Segundo o quadro da delegação, a permissão de serviço público é:",
  options:["Contrato administrativo, com licitação obrigatória em qualquer modalidade",
           "Ato administrativo, sem licitação",
           "Contrato administrativo, com licitação apenas na concorrência",
           "Ato administrativo precário, com licitação obrigatória"],
  answer:0,
  why:"Permissão de serviço público = contrato administrativo; permissão de uso de bem público = ato administrativo."},

S6:{t:"mc", instr:"A Administração reconhece a conveniência do serviço, mas não sua necessidade e essencialidade, e por isso o presta diretamente ou o delega a concessionários e permissionários. Trata-se de serviço:",
  options:["De utilidade pública","Propriamente dito","Singular (uti singuli)","Econômico"],
  answer:0,
  why:"Nos propriamente ditos a Administração reconhece a essencialidade e presta diretamente, sem delegação a terceiros."},

S7:{t:"wordbank", instr:"Monte o conceito de concessão de serviço público",
  target:["É","a","delegação","da","prestação","de","serviço","público","feita","pelo","poder","concedente","mediante","licitação","por","prazo","determinado"],
  extra:["indeterminado","ato","unilateral","sem"],
  why:"Delegação pelo poder concedente, mediante licitação, por sua conta e risco e por prazo determinado — nunca indeterminado."},

S8:{t:"mc", instr:"A concessão de serviço público exige licitação em qual modalidade?",
  options:["Concorrência ou diálogo competitivo","Qualquer modalidade","Pregão ou concorrência","Concurso"],
  answer:0,
  why:"Qualquer modalidade é a regra da permissão; na autorização não há licitação."},

S9:{t:"multi", instr:"Marque as formas de extinção da concessão listadas no resumo",
  options:["Advento do termo contratual",
           "Encampação",
           "Caducidade",
           "Rescisão",
           "Anulação",
           "Falência ou extinção da empresa concessionária",
           "Falecimento ou incapacidade do titular, no caso de empresa individual",
           "Intervenção",
           "Reversão"],
  answers:[0,1,2,3,4,5,6],
  why:"A intervenção não extingue a concessão — é a medida que o poder concedente pode tomar no lugar de decretar a caducidade; a reversão é a transferência dos bens ao poder concedente ao término do contrato."},

S10:{t:"match", instr:"Correlacione cada instituto à sua descrição",
  pairs:[["Advento do termo contratual","Atingimento do prazo previsto no contrato"],
         ["Encampação","Retomada do serviço pelo poder concedente, por interesse público, com lei autorizativa e indenização prévia"],
         ["Caducidade","O contratado descumpre obrigações contratuais"],
         ["Rescisão","O contratado entra na justiça para sair fora"],
         ["Anulação","Há vício de legalidade"],
         ["Reversão","Transferência ao poder concedente dos bens do concessionário afetados ao serviço, ao término do contrato"]],
  why:"Encampação é retomada por interesse público; caducidade é punição pelo descumprimento contratual."},

S11:{t:"mc", instr:"A caducidade da concessão é declarada por qual instrumento?",
  options:["Decreto do poder concedente","Portaria do poder concedente","Sentença judicial","Resolução do interventor"],
  answer:0,
  why:"O resumo grifa: a caducidade será declarada por decreto — não é portaria."},

S12:{t:"sort", instr:"O requisito é da encampação ou da caducidade?",
  buckets:["Encampação","Caducidade"],
  items:[["Retomada do serviço por motivo de interesse público",0],
         ["Lei autorizativa específica",0],
         ["Prévio pagamento da indenização",0],
         ["Descumprimento de obrigações contratuais pelo concessionário",1],
         ["Notificação da concessionária para corrigir as falhas",1],
         ["Processo administrativo com ampla defesa e contraditório, seguido de decreto",1]],
  why:"Na questão-exemplo do TJ PR, a caducidade foi declarada por decreto do Prefeito, independentemente de indenização prévia."},

S13:{t:"gap", instr:"Complete os prazos da intervenção",
  before:"Declarada a intervenção, o procedimento administrativo deve ser instaurado no prazo de trinta dias e concluído no prazo de até ",
  after:" dias, sob pena de considerar-se inválida a intervenção.",
  options:["cento e oitenta","noventa","trezentos e sessenta"], answer:0,
  why:"30 dias para instaurar, 180 para concluir."},

S14:{t:"mc", instr:"Sobre a intervenção na concessão, assinale a afirmativa correta:",
  options:["Não é ato punitivo e, por isso, dispensa ampla defesa e contraditório prévios; decretado o ato interventivo, fica assegurado o direito de ampla defesa",
           "É ato punitivo e exige ampla defesa e contraditório prévios",
           "Extingue a concessão e transfere ao poder concedente todos os bens reversíveis",
           "Dispensa decreto, podendo ser determinada por simples ofício do poder concedente"],
  answer:0,
  why:"A intervenção é alternativa à caducidade e se faz por decreto, com designação do interventor, prazo, objetivos e limites."},

S15:{t:"match", instr:"Correlacione cada espécie de concessão à sua forma de remuneração",
  pairs:[["Concessão simples","O delegatário é remunerado apenas pelas tarifas pagas pelos usuários"],
         ["Concessão precedida de obra","O particular realiza a obra às suas expensas e é remunerado depois pela exploração do serviço decorrente dela"],
         ["Concessão patrocinada","Contraprestação do Estado somada à tarifa do usuário"],
         ["Concessão administrativa","Remuneração integral do Estado, que é usuário direto ou indireto"]],
  why:"Simples e precedida de obra são concessão comum (Lei 8.987/95); patrocinada e administrativa são concessão especial — PPP (Lei 11.079/04)."},

S16:{t:"sort", instr:"A característica é da concessão comum ou da concessão especial (PPP)?",
  buckets:["Concessão comum","Concessão especial (PPP)"],
  items:[["Submete-se à Lei 8.987/95",0],
         ["Submete-se à Lei 11.079/04",1],
         ["O delegatário é remunerado apenas pelas tarifas pagas pelos usuários",0],
         ["Sempre haverá contraprestação pecuniária do Poder Público ao parceiro privado",1],
         ["Subdivide-se em simples e precedida de obra",0],
         ["Pode ser patrocinada ou administrativa",1],
         ["A lei não estabelece prazo máximo de vigência do contrato",0],
         ["Prazo mínimo de 5 e máximo de 35 anos, incluindo eventual prorrogação",1]],
  why:"Sem contraprestação pecuniária do parceiro público não existe PPP: o que se tem é concessão comum."},

S17:{t:"gap", instr:"Complete o prazo máximo das PPP",
  before:"Na concessão especial (PPP), a Lei 11.079/04 estabelece prazo mínimo de 5 anos e máximo de ",
  after:" anos, incluindo eventual prorrogação.",
  options:["35","30","20"], answer:0,
  why:"Na concessão comum, a Lei 8.987/95 não estabelece prazo máximo."},

S18:{t:"multi", instr:"Marque as hipóteses em que a interrupção do serviço NÃO caracteriza descontinuidade",
  options:["Interrupção em situação de emergência",
           "Interrupção, após prévio aviso, motivada por razões de ordem técnica",
           "Interrupção, após prévio aviso, motivada por razões de segurança das instalações",
           "Interrupção, após prévio aviso, por inadimplemento do usuário, considerado o interesse da coletividade",
           "Corte de energia de prédio onde funciona hospital municipal inadimplente há 120 dias",
           "Interrupção sem qualquer aviso, por conveniência da concessionária"],
  answers:[0,1,2,3],
  why:"O corte no hospital municipal é o exemplo do REsp 1.755.345 em que a concessionária agiu erradamente: sendo o devedor ente público, não cabe corte indiscriminado."},

S19:{t:"mc", instr:"A transferência de concessão ou de controle societário da concessionária sem a prévia anuência do poder concedente implica:",
  options:["A caducidade da concessão","A anulação da concessão","A encampação da concessão","A intervenção na concessão"],
  answer:0,
  why:"O resumo registra entre parênteses: não é anulação."},

S20:{t:"match", instr:"Correlacione cada súmula ou julgado ao seu enunciado",
  pairs:[["STF, Súmula Vinculante 41","O serviço de iluminação pública não pode ser remunerado mediante taxa"],
         ["STJ, Súmula 407","É legítima a cobrança da tarifa de água fixada de acordo com as categorias de usuários e as faixas de consumo"],
         ["STF, ADC 57","Concessionárias de serviços públicos podem terceirizar quaisquer de suas atividades, inclusive as atividades-fim"],
         ["STJ, REsp 1.412.433","Cabe o corte de energia, com prévio aviso, por energia recuperada do período de 90 dias anterior à constatação da fraude"],
         ["STJ, REsp 1.755.345","Sendo o devedor ente público, não cabe corte indiscriminado que atinja hospitais, creches, escolas e iluminação pública"]],
  why:"O fundamento da SV 41 é a caracterização da iluminação pública como serviço UNIVERSAL — e taxas só cabem por poder de polícia ou por serviços específicos e divisíveis."}
};

for(var i=0;i<QS.length;i++) EX["T"+i]={t:"ce", qi:i};

var TEC = [
  ["Caderno CEBRASPE — Direito Administrativo 09","https://www.tecconcursos.com.br/s/Q23lY1","Q23lY1"],
  ["Caderno FCC — Direito Administrativo 09","https://www.tecconcursos.com.br/s/Q23lYT","Q23lYT"],
  ["Caderno FGV — Direito Administrativo 09","https://www.tecconcursos.com.br/s/Q23lYY","Q23lYY"],
  ["Caderno VUNESP — Direito Administrativo 09","https://www.tecconcursos.com.br/s/Q23lYi","Q23lYi"],
  ["Caderno AOCP — Direito Administrativo 09","https://www.tecconcursos.com.br/s/Q23lYH","Q23lYH"],
  ["Caderno IBFC — Direito Administrativo 09","https://www.tecconcursos.com.br/s/Q27ZtW","Q27ZtW"],
  ["Caderno FUNDATEC — Direito Administrativo 09","https://www.tecconcursos.com.br/s/Q27Zte","Q27Zte"]
];
var TECNOTA = "Três fronteiras respondem pela maioria dos erros deste assunto. A primeira é o quadro da delegação: concessão e permissão são contratos administrativos e a autorização é ato; só a concessão não pode ser revogada e só nela o contratado tem de ser pessoa jurídica ou consórcio de empresas; a licitação da concessão é por concorrência ou diálogo competitivo, a da permissão admite qualquer modalidade e na autorização não há licitação. Guarde junto a OBS que a banca inverte: permissão de serviço público é CONTRATO, permissão de uso de bem público é ATO. A segunda é o par encampação/caducidade, com os números do próprio resumo: encampação é retomada por interesse público, com lei autorizativa específica e prévio pagamento da indenização; caducidade é descumprimento de obrigações contratuais, com notificação para corrigir as falhas, processo administrativo com ampla defesa e contraditório e declaração por DECRETO (não portaria); e a intervenção, que o poder concedente pode promover no lugar de decretar a caducidade, não é ato punitivo e por isso dispensa ampla defesa e contraditório prévios, mas exige procedimento instaurado em 30 dias e concluído em até 180 dias, sob pena de invalidade. A terceira é a linha entre concessão comum e concessão especial: a Lei 8.987/95 não fixa prazo máximo, a Lei 11.079/04 fixa de 5 a 35 anos incluindo prorrogação; sem contraprestação pecuniária do parceiro público não existe PPP, e sim concessão comum; a patrocinada soma contraprestação do Estado e tarifa do usuário, a administrativa é remuneração integral do Estado; e a maior parte das PPP está nos governos estaduais e municipais, não no federal. Vale ainda decorar as trocas de princípios (generalidade é universalidade e isonomia; atualidade é modernidade de técnicas e equipamentos) e os exemplos de uti universi (pavimentação de ruas, iluminação pública) contra os de uti singuli (energia e água domiciliares, linha telefônica).";

var UNITS = [
  {n:1, title:"Serviço público, princípios e delegação", cvar:"u1", lessons:[
    {id:"K1", type:"teoria", title:"Do conceito ao quadro de concessão, permissão e autorização", xp:10, data:"V1"},
    {id:"K2", type:"drill",  title:"Praticar · conceito e classificação dos serviços",  xp:25, data:["S6","S1","T0","T1","T2","T3","T4"]},
    {id:"K3", type:"drill",  title:"Praticar · os cinco princípios",                    xp:25, data:["S2","S3","T5","T6","T7","T8","T9"]},
    {id:"K4", type:"drill",  title:"Praticar · delegação e uti universi/singuli",       xp:25, data:["S4","S5","T10","T11","T12","T13","T14","T15","T16","T17"]},
    {id:"K5", type:"flash",  title:"Flashcards · conceito, princípios e delegação",     xp:15, data:[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]}
  ]},
  {n:2, title:"Tarifa, extinção e intervenção", cvar:"u2", lessons:[
    {id:"K6", type:"teoria", title:"Política tarifária, as sete extinções e a intervenção", xp:10, data:"V2"},
    {id:"K7", type:"drill",  title:"Praticar · concessão e política tarifária",         xp:25, data:["S7","S8","T18","T19","T20","T21","T22","T23","T24","T25","T26"]},
    {id:"K8", type:"drill",  title:"Praticar · encampação, caducidade e rescisão",      xp:25, data:["S9","S10","S11","S12","T27","T28","T29","T30","T31","T32"]},
    {id:"K9", type:"drill",  title:"Praticar · intervenção e seus prazos",              xp:25, data:["S13","S14","T33","T34","T35","T36","T37"]},
    {id:"K10",type:"flash",  title:"Flashcards · tarifa, extinção e intervenção",       xp:15, data:[18,19,20,21,22,23,24,25,26,27,28,29]}
  ]},
  {n:3, title:"Concessão comum, PPP e conceitos importantes", cvar:"u3", lessons:[
    {id:"K11",type:"teoria", title:"Comum × especial e o bloco de \"lei seca\"",         xp:10, data:"V3"},
    {id:"K12",type:"drill",  title:"Praticar · concessão comum e concessão especial",   xp:25, data:["S15","S16","T38","T39","T40","T41","T42"]},
    {id:"K13",type:"drill",  title:"Praticar · prazos, reversão e descontinuidade",     xp:25, data:["S17","S18","T43","T44","T45","T46"]},
    {id:"K14",type:"drill",  title:"Praticar · súmulas, subconcessão e terceirização",  xp:25, data:["S19","S20","T47","T48","T49","T50","T51"]},
    {id:"K15",type:"flash",  title:"Flashcards · PPP, súmulas e reversão",              xp:15, data:[30,31,32,33,34,35,36,37,38,39]}
  ]},
  {n:4, title:"Fixação", cvar:"u4", lessons:[
    {id:"Krev",type:"review",title:"Revisão geral do módulo",                           xp:60, data:null},
    {id:"K16", type:"missao", title:"Missão TEC Concursos",                              xp:15, data:null},
    {id:"K17", type:"prova",  title:"Simulado cronometrado",                             xp:100, data:null}
  ]}
];

/* ---------- comentários, extraídos do Resumo 09 de Direito Administrativo (Radegondes) ---------- */
var COM={
0:"<p>Certo — é a frase de abertura do resumo: o serviço público <b>é incumbência do Estado, conforme previsão expressa na Constituição Federal de 1988, podendo ser prestado diretamente pelo poder público ou sob o regime de concessão ou permissão</b>.</p><p>Três palavras sustentam o conceito: <b>incumbência do Estado</b>, <b>diretamente</b> e <b>concessão ou permissão</b>. Note que o regime de delegação citado aqui é o de <b>concessão ou permissão</b> — a autorização aparece no quadro da delegação, não neste enunciado constitucional.</p><p class='fb-fonte'>Resumo 09 · <i>Serviço Público</i></p>",
1:"<p>Certo. O conteúdo é exatamente o do resumo: a prestação do serviço público é <b>incumbência do Estado</b>, por <b>previsão expressa na CF/88</b>, <b>diretamente pelo poder público ou sob o regime de concessão ou permissão</b> — e, nas duas formas de delegação, a <b>licitação é obrigatória</b> (na concessão, concorrência ou diálogo competitivo; na permissão, qualquer modalidade).</p><p>Se a banca trocar \"concessão ou permissão\" por \"autorização\", a assertiva cai: a autorização é <b>ato administrativo</b> e nela <b>não há licitação</b>.</p><p class='fb-fonte off'>Não consta do Resumo 09 — o material afirma a previsão expressa na CF/88 e a exigência de licitação, mas não indica o número do dispositivo; o art. 175 vem de fora do resumo.</p>",
2:"<p>Errado — a definição é a dos serviços <b>de utilidade pública</b>, não a dos <b>propriamente ditos</b>. No quadro do resumo: <b>de utilidade pública são aqueles em que a Administração reconhece a conveniência, mas não sua necessidade e essencialidade, e, por isso, ou os presta diretamente à sociedade ou os delega para que sejam executados por terceiros (concessionários e permissionários)</b>.</p><p>Os <b>propriamente ditos</b> são o oposto: a Administração presta <b>diretamente à comunidade, sem delegação a terceiros, por reconhecer sua essencialidade</b>. A palavra de corte é <b>essencialidade</b>.</p><p class='fb-fonte'>Resumo 09 · <i>Classificação dos serviços públicos</i></p>",
3:"<p>Certo, é a segunda metade da definição do quadro: nos serviços <b>de utilidade pública</b> a Administração <b>ou os presta diretamente à sociedade ou os delega para que sejam executados por terceiros (concessionários e permissionários)</b>.</p><p>O pressuposto é o reconhecimento da <b>conveniência</b>, mas <b>não</b> da <b>necessidade e essencialidade</b> do serviço — é isso que abre a porta da delegação.</p><p class='fb-fonte'>Resumo 09 · <i>Classificação dos serviços públicos</i></p>",
4:"<p>Certo pela letra do quadro: os serviços <b>propriamente ditos</b> são <b>os que a Administração presta diretamente à comunidade, sem delegação a terceiros, por reconhecer sua essencialidade</b>.</p><p>Guarde o par por contraste: <b>essencialidade reconhecida</b> → presta direto, sem delegar; <b>apenas conveniência</b> → pode delegar a concessionários e permissionários.</p><p class='fb-fonte'>Resumo 09 · <i>Classificação dos serviços públicos</i></p>",
5:"<p>Certo, é a definição literal do resumo: o princípio da continuidade, <b>também chamado de princípio da permanência, impõe que o serviço público, uma vez instituído, seja prestado de forma permanente, sem interrupção</b>.</p><p>Esse princípio é a base do bloco dos <b>Conceitos Importantes</b> sobre interrupção: não se caracteriza descontinuidade a interrupção em <b>situação de emergência</b>, ou, <b>após prévio aviso</b>, por <b>razões de ordem técnica ou de segurança das instalações</b> ou por <b>inadimplemento do usuário</b>, considerado o interesse da coletividade.</p><p class='fb-fonte'>Resumo 09 · <i>Princípio da Continuidade</i></p>",
6:"<p>Errado por troca de princípio. O que o resumo descreve como <b>modernidade das técnicas, dos equipamentos, das instalações e a sua conservação, bem como a melhoria e expansão do serviço</b> é o princípio da <b>ATUALIDADE</b>.</p><p>A <b>generalidade</b> é outra coisa: é <b>atinente aos aspectos da universalidade e da isonomia</b>, e a característica de ser <b>universal</b> garante que o serviço seja <b>ofertado da forma mais abrangente possível</b>.</p><p class='fb-fonte'>Resumo 09 · <i>Princípio da Generalidade / Princípio da Atualidade</i></p>",
7:"<p>Errado — é a mesma troca do item anterior, na direção inversa. <b>Universalidade e isonomia</b>, com a oferta <b>da forma mais abrangente possível</b>, é o princípio da <b>GENERALIDADE</b>.</p><p>A <b>atualidade</b> diz respeito à <b>modernidade das técnicas, dos equipamentos, das instalações e a sua conservação, bem como a melhoria e expansão do serviço</b>. Um atalho: generalidade fala de <b>quem</b> recebe o serviço; atualidade fala de <b>como</b> ele é prestado.</p><p class='fb-fonte'>Resumo 09 · <i>Princípio da Atualidade / Princípio da Generalidade</i></p>",
8:"<p>Certo, é a definição do resumo: pela modicidade, <b>o valor pago pela prestação dos serviços deve ser estabelecido segundo padrões de razoabilidade, mediante tarifas mais baixas possíveis cobradas dos usuários</b>.</p><p>O fecho da definição explica o porquê: <b>a fim de manter a prestação do serviço à maior parte possível da coletividade</b>. É esse princípio que reaparece na política tarifária, quando o resumo admite <b>receitas alternativas</b> previstas no edital <b>com vistas a favorecer a modicidade das tarifas</b>.</p><p class='fb-fonte'>Resumo 09 · <i>Princípio da Modicidade</i></p>",
9:"<p>Certo pela letra do resumo: a economicidade <b>é a união da qualidade, celeridade e menor custo na prestação do serviço ou no trato com os bens públicos</b>.</p><p>São <b>três</b> elementos somados — se a assertiva deixar de fora a <b>celeridade</b> ou trocar <b>menor custo</b> por \"custo zero\", ela se desfaz. Não confunda com a <b>modicidade</b>, que olha para o <b>valor da tarifa paga pelo usuário</b>.</p><p class='fb-fonte'>Resumo 09 · <i>Princípio da Economicidade</i></p>",
10:"<p>Certo, é a primeira linha do quadro <b>DELEGAÇÃO DO SERVIÇO PÚBLICO</b>: <b>concessão = contrato administrativo</b>, <b>permissão = contrato administrativo</b>, <b>autorização = ato administrativo</b>.</p><p>Essa linha é a origem de quase tudo o que vem depois no quadro: por serem <b>contratos</b>, concessão e permissão exigem <b>licitação</b>; por ser <b>ato</b> unilateral, na autorização <b>não há licitação</b>.</p><p class='fb-fonte'>Resumo 09 · <i>Delegação do Serviço Público</i></p>",
11:"<p>Errado — a assertiva inverteu a segunda linha do quadro. No resumo: na <b>concessão predomina o interesse público</b>; na <b>permissão</b>, há <b>interesse público e privado</b>; e na <b>autorização predomina o interesse privado</b>.</p><p>A lógica ajuda a fixar: quanto mais o interesse é do particular, mais frágil é o vínculo — a autorização é <b>ato</b>, <b>sem licitação</b> e <b>revogável</b> por ser <b>título precário</b>.</p><p class='fb-fonte'>Resumo 09 · <i>Delegação do Serviço Público</i></p>",
12:"<p>Certo, é a quarta linha do quadro: a <b>concessão não pode ser revogada</b>, enquanto a <b>permissão</b> e a <b>autorização podem ser revogadas</b>, pois constituem <b>título precário</b>.</p><p>Cuidado com o vocabulário: a concessão não é revogável, mas pode ser <b>extinta</b> — por advento do termo, <b>encampação</b>, <b>caducidade</b>, rescisão, anulação, falência ou extinção da empresa e falecimento ou incapacidade do titular, no caso de empresa individual.</p><p class='fb-fonte'>Resumo 09 · <i>Delegação do Serviço Público</i></p>",
13:"<p>Errado — a assertiva inverteu a última linha do quadro. No resumo: na <b>concessão o contratado só pode ser Pessoa Jurídica (ou consórcio de empresas)</b>; na <b>permissão</b> e na <b>autorização o contratado pode ser pessoa física ou jurídica</b>.</p><p>Isso combina com o conceito de concessão, que exige delegação <b>à pessoa jurídica (ou consórcio de empresas) que demonstre capacidade para seu desempenho</b>. Guarde a regra de ouro: <b>concessionário nunca é pessoa física</b>.</p><p class='fb-fonte'>Resumo 09 · <i>Delegação do Serviço Público</i></p>",
14:"<p>Errado, e a inversão é exatamente a que o resumo antecipa na OBS do quadro: <b>Permissão de Serviço Público = CONTRATO administrativo</b> e <b>Permissão de Uso de Bem Público = ATO administrativo</b>.</p><p>Fixe pelo objeto: se o que se delega é <b>serviço</b>, é <b>contrato</b>; se o que se permite é o uso de um <b>bem</b>, é <b>ato</b>. A assertiva trocou os dois.</p><p class='fb-fonte'>Resumo 09 · <i>Delegação do Serviço Público — OBS</i></p>",
15:"<p>Certo nas duas partes. O resumo define os serviços coletivos (<b>uti universi</b>) como <b>aqueles serviços prestados a grupamentos indeterminados de indivíduos</b> e acrescenta que <b>os indivíduos não têm direito subjetivo próprio para sua obtenção</b>.</p><p>Os exemplos dele: <b>pavimentação de ruas</b>, <b>iluminação pública</b>, <b>implantação do serviço de abastecimento de água</b> e <b>implantação do serviço de prevenção de doenças</b>.</p><p class='fb-fonte'>Resumo 09 · <i>Serviços Coletivos (uti universi)</i></p>",
16:"<p>Errado — <b>pavimentação de ruas</b> e <b>iluminação pública</b> são os exemplos de serviços <b>coletivos (uti universi)</b> no resumo, e não de uti singuli.</p><p>Os exemplos de <b>uti singuli</b> são outros: <b>energia domiciliar</b>, <b>água domiciliar</b> e <b>uso de linha telefônica</b>. O critério é o da <b>mensurabilidade</b>: no uti singuli é mensurável a utilização por cada indivíduo, que por isso <b>tem direito subjetivo</b> à prestação.</p><p class='fb-fonte'>Resumo 09 · <i>Serviços Coletivos (uti universi) / Serviços Singulares (uti singuli)</i></p>",
17:"<p>Certo, é a definição do resumo somada ao exemplo dele: os serviços singulares <b>são aqueles prestados a destinatários individualizados</b>, é <b>mensurável a utilização por cada um dos indivíduos</b> e <b>os indivíduos possuem direito subjetivo para sua obtenção</b>; o exemplo do quadro comparativo é <b>energia domiciliar</b>.</p><p>O material acrescenta a consequência prática: se o serviço é prestado a outro na <b>mesma situação jurídica</b>, o interessado pode pleitear que a prestação também o alcance — senão estaria vulnerado o princípio da <b>impessoalidade</b> (art. 37 da CF), cabendo recorrer à <b>via judicial</b>.</p><p class='fb-fonte'>Resumo 09 · <i>Serviços Singulares (uti singuli)</i></p>",
18:"<p>Errado no prazo. O conceito do resumo termina com <b>por sua conta e risco e por PRAZO DETERMINADO</b>.</p><p>A definição completa é: <b>delegação da prestação de serviço público feita pelo poder concedente (União, Estado, DF ou Município) mediante licitação, na modalidade concorrência ou diálogo competitivo, à pessoa jurídica (ou consórcio de empresas) que demonstre capacidade para seu desempenho, por sua conta e risco e por prazo determinado</b>. Não confunda: a Lei 8.987/95 <b>não fixa prazo máximo</b> de vigência, mas o contrato tem de ter <b>prazo determinado</b>.</p><p class='fb-fonte'>Resumo 09 · <i>Concessão de Serviço Público</i></p>",
19:"<p>Certo nas duas metades, conforme o quadro da delegação: na <b>concessão a licitação é obrigatória (concorrência ou diálogo competitivo)</b> e na <b>permissão a licitação é obrigatória (qualquer modalidade)</b>.</p><p>Complete o quadro com a terceira figura: na <b>autorização não há licitação</b>, porque ela é <b>ato administrativo</b> e nela predomina o <b>interesse privado</b>.</p><p class='fb-fonte'>Resumo 09 · <i>Delegação do Serviço Público</i></p>",
20:"<p>Errado por restrição indevida. O resumo define o poder concedente no próprio conceito de concessão, e ele abrange os <b>quatro</b> entes: a delegação é feita <b>pelo poder concedente (União, Estado, DF ou Município)</b>.</p><p>Essa sigla <b>U, E, DF, M</b> reaparece em três lugares do material: na obrigação de restabelecer o <b>equilíbrio econômico-financeiro</b> em caso de alteração unilateral, no conceito de <b>concessão comum</b> e no de <b>reversão</b> dos bens ao término do contrato.</p><p class='fb-fonte'>Resumo 09 · <i>Concessão de Serviço Público</i></p>",
21:"<p>Certo, é a abertura literal da política tarifária: <b>a tarifa do serviço público concedido será fixada pelo preço da proposta vencedora da licitação e preservada pelas regras de revisão previstas na lei, no edital e no contrato</b>.</p><p>Guarde o trio <b>lei, edital e contrato</b> — é dele que o resumo tira a conclusão de que o concessionário não pode mexer na tarifa por conta própria.</p><p class='fb-fonte'>Resumo 09 · <i>Da Política Tarifária</i></p>",
22:"<p>Errado — o resumo afirma justamente o contrário: <b>os concessionários de serviço público não detêm a liberdade própria da iniciativa privada para alterar o valor da tarifa cobrada dos usuários, já que tal tarifa se submete aos termos da lei, do edital e do contrato</b>.</p><p>A tarifa é fixada pelo <b>preço da proposta vencedora da licitação</b> e só muda pelas <b>regras de revisão</b> previstas na lei, no edital e no contrato — por exemplo, na criação ou alteração de tributos ou na alteração unilateral que afete o equilíbrio econômico-financeiro.</p><p class='fb-fonte'>Resumo 09 · <i>Da Política Tarifária</i></p>",
23:"<p>Certo, é a observação 02 da política tarifária, palavra por palavra: <b>ressalvados os impostos sobre a renda, a criação, alteração ou extinção de quaisquer tributos ou encargos legais, após a apresentação da proposta, quando comprovado seu impacto, implicará a revisão da tarifa, para mais ou para menos, conforme o caso</b>.</p><p>Três detalhes que a banca mexe: a ressalva dos <b>impostos sobre a renda</b>, o marco temporal (<b>após a apresentação da proposta</b>) e a bidirecionalidade (<b>para mais ou para menos</b>).</p><p class='fb-fonte'>Resumo 09 · <i>Da Política Tarifária — Observações</i></p>",
24:"<p>Errado por inversão da observação 04: <b>as tarifas poderão ser diferenciadas em função das características técnicas e dos custos específicos provenientes do atendimento aos distintos segmentos de usuários</b>.</p><p>Essa permissão é a mesma ideia da <b>Súmula 407 do STJ</b> citada nos Conceitos Importantes: <b>é legítima a cobrança da tarifa de água fixada de acordo com as categorias de usuários e as faixas de consumo</b>.</p><p class='fb-fonte'>Resumo 09 · <i>Da Política Tarifária — Observações</i></p>",
25:"<p>Errado — não existe essa vedação; o resumo autoriza expressamente as receitas alternativas. Observação 06 da política tarifária, repetida no <b>Tome Nota 12</b>: <b>no atendimento às peculiaridades de cada serviço público, poderá o poder concedente prever, em favor da concessionária, no edital de licitação, a possibilidade de outras fontes provenientes de receitas alternativas, com vistas a favorecer a modicidade das tarifas</b>.</p><p>Repare no lugar da previsão: é <b>no edital de licitação</b>, e a finalidade declarada é a <b>modicidade</b> — o princípio das tarifas mais baixas possíveis.</p><p class='fb-fonte'>Resumo 09 · <i>Da Política Tarifária — Observações</i></p>",
26:"<p>Errado — falta a condição. A observação 05 exige previsão legal: <b>havendo previsão legal específica, a cobrança da tarifa do serviço público concedido poderá ser condicionada à existência de serviço público alternativo e gratuito para o usuário</b>.</p><p>O <b>Tome Nota 03</b> reforça com o advérbio: <b>SOMENTE com previsão legal específica</b> a cobrança da tarifa poderá ser condicionada à existência de serviço público alternativo e gratuito. A expressão \"ainda que sem previsão legal específica\" é o que derruba a assertiva.</p><p class='fb-fonte'>Resumo 09 · <i>Da Política Tarifária — Observações / Conceitos Importantes — Tome Nota 03</i></p>",
27:"<p>Certo, com os três requisitos da observação 01 das formas de extinção: a <b>encampação é a retomada do serviço pelo poder concedente durante o prazo da concessão</b>, <b>por motivo de interesse público</b>, <b>mediante lei autorizativa específica</b> e <b>após prévio pagamento da indenização</b>.</p><p>É o gabarito da questão-exemplo do resumo (FGV — CM Aracaju 2021): o Município Alfa, no contrato de <b>abastecimento de água potável</b> com a sociedade empresária Gama, retoma o serviço <b>por encampação, mediante lei autorizativa específica e após prévio pagamento da indenização</b> à concessionária.</p><p class='fb-fonte'>Resumo 09 · <i>Formas de Extinção da Concessão — Observações</i></p>",
28:"<p>Errado: a descrição é da <b>encampação</b>. No resumo, <b>caducidade ocorre quando o contratado descumpre obrigações contratuais</b>, enquanto a <b>encampação é a retomada do serviço pelo poder concedente durante o prazo da concessão, por motivo de interesse público, mediante lei autorizativa específica e após prévio pagamento da indenização</b>.</p><p>Um atalho pelas consequências: encampação tem <b>lei autorizativa</b> e <b>indenização prévia</b>; a caducidade, no gabarito da questão do TJ PR, se dá <b>independentemente de indenização prévia</b>, porque a falta é do concessionário.</p><p class='fb-fonte'>Resumo 09 · <i>Formas de Extinção da Concessão — Observações</i></p>",
29:"<p>Errado no instrumento, e o resumo grifa a diferença entre parênteses: <b>a caducidade será declarada por decreto (não é portaria) do poder concedente</b>.</p><p>As três condições, na ordem: <b>1º)</b> a concessionária deverá ser <b>notificada para corrigir as falhas</b>; <b>2º)</b> não atendida a notificação, deverá ser instaurado <b>processo administrativo</b>, assegurada <b>ampla defesa + contraditório</b>; <b>3º)</b> declaração por <b>decreto</b>. Na questão-exemplo do TJ PR, o gabarito fala expressamente em <b>declaração por decreto do Prefeito</b>.</p><p class='fb-fonte'>Resumo 09 · <i>Formas de Extinção da Concessão — Observações (caducidade)</i></p>",
30:"<p>Certo: são os dois primeiros passos da observação 02. <b>1º) A concessionária deverá ser notificada para corrigir as falhas. 2º) Não sendo atendida a notificação, deverá ser instaurado processo administrativo, sendo assegurada a ampla defesa + contraditório.</b></p><p>Falta o terceiro, que é onde a banca costuma errar de propósito: a caducidade <b>será declarada por decreto</b> do poder concedente — <b>não é portaria</b>.</p><p class='fb-fonte'>Resumo 09 · <i>Formas de Extinção da Concessão — Observações (caducidade)</i></p>",
31:"<p>Certo, é a lista completa do resumo: <b>advento do termo contratual</b> (atingimento do prazo previsto no contrato), <b>encampação</b> (retomada do serviço pelo poder concedente), <b>caducidade</b> (quando o contratado descumpre obrigações contratuais), <b>rescisão</b> (quando o contratado entra na justiça para sair fora), <b>anulação</b> (quando tem vício de legalidade), <b>falência ou extinção da empresa concessionária</b> e <b>falecimento ou incapacidade do titular, no caso de empresa individual</b>.</p><p>Duas figuras que o enunciado costuma enfiar na lista e <b>não</b> pertencem a ela: a <b>intervenção</b>, que é alternativa à caducidade e não extingue a concessão, e a <b>reversão</b>, que é a transferência dos bens ao poder concedente <b>ao término</b> do contrato.</p><p class='fb-fonte'>Resumo 09 · <i>Formas de Extinção da Concessão</i></p>",
32:"<p>Errado, e o resumo dedica uma observação inteira a isso: <b>caducidade dos contratos ≠ caducidade dos atos administrativos</b>.</p><p>A diferença está na causa. Nos <b>contratos</b>, a caducidade <b>ocorre quando o contratado descumpre obrigações contratuais</b>. Nos <b>atos administrativos</b>, <b>ocorre quando uma norma jurídica posterior torna inviável a permanência da situação antes permitida pelo ato</b> — lá é falta do particular, aqui é mudança da lei.</p><p class='fb-fonte'>Resumo 09 · <i>Formas de Extinção da Concessão — Observações 03 e 04</i></p>",
33:"<p>Certo, e junta duas passagens do resumo. A primeira: <b>no lugar de decretar a caducidade, o Poder Concedente pode promover a intervenção, designando o interventor, o prazo da intervenção e os objetivos da medida</b>. A segunda, na observação 02: <b>a intervenção far-se-á por decreto do poder concedente, que conterá a designação do interventor, o prazo da intervenção e os objetivos e limites da medida</b>.</p><p>É o gabarito da questão-exemplo (FGV — OAB 2020) do serviço de <b>veículos leves sobre trilhos</b> do Município Beta: cabe a <b>intervenção</b>, por <b>decreto do poder concedente</b>, com <b>designação do interventor, prazo, objetivos e limites</b>.</p><p class='fb-fonte'>Resumo 09 · <i>Da Intervenção</i></p>",
34:"<p>Errado logo na primeira observação da intervenção: <b>a intervenção não é ato punitivo e, por isso, não há exigência de ampla defesa e contraditórios prévios</b>.</p><p>Mas o resumo completa, e essa segunda parte é a que a banca esconde: <b>uma vez decretado o ato interventivo, fica assegurado o direito de ampla defesa</b>. Ou seja, a ampla defesa existe — só não é <b>prévia</b>. Compare com a <b>caducidade</b>, que é punitiva e exige processo administrativo com ampla defesa e contraditório <b>antes</b> do decreto.</p><p class='fb-fonte'>Resumo 09 · <i>Da Intervenção — Observações</i></p>",
35:"<p>Certo nos dois prazos, conforme a observação 03: <b>declarada a intervenção, o poder concedente deverá, no prazo de trinta dias, instaurar procedimento administrativo para comprovar as causas determinantes da medida e apurar responsabilidades, assegurado o direito de ampla defesa</b>, e <b>esse procedimento administrativo deverá ser concluído no prazo de até cento e oitenta dias, sob pena de considerar-se inválida a intervenção</b>.</p><p>Grave o par <b>30 / 180</b> e a sanção: estourado o prazo de conclusão, a <b>intervenção é inválida</b>.</p><p class='fb-fonte'>Resumo 09 · <i>Da Intervenção — Observações</i></p>",
36:"<p>Errado nos dois números. Os prazos do resumo são <b>trinta dias</b> para <b>instaurar</b> o procedimento administrativo e <b>até cento e oitenta dias</b> para <b>concluí-lo</b>, <b>sob pena de considerar-se inválida a intervenção</b>.</p><p>Sessenta e cento e vinte são os números que a banca inventa para esse item. Fixe <b>30 / 180</b>.</p><p class='fb-fonte'>Resumo 09 · <i>Da Intervenção — Observações</i></p>",
37:"<p>Certo pela letra da observação 04: <b>se ficar comprovado que a intervenção não observou os pressupostos legais e regulamentares será declarada sua nulidade, devendo o serviço ser imediatamente devolvido à concessionária, sem prejuízo de seu direito à indenização</b>.</p><p>São três consequências encadeadas: <b>nulidade</b>, <b>devolução imediata</b> do serviço e <b>direito à indenização</b> — que a assertiva mantém na ordem correta.</p><p class='fb-fonte'>Resumo 09 · <i>Da Intervenção — Observações</i></p>",
38:"<p>Certo. O resumo registra que a concessão comum <b>submete-se à lei 8.987/95</b> e que ela <b>subdivide-se em Concessões Simples ou Concessões Precedidas de Obra</b>.</p><p>A diferença entre as duas está na remuneração: na <b>simples</b>, o delegatário é remunerado <b>apenas pelas tarifas pagas pelos usuários</b>; na <b>precedida de obra</b>, ele <b>realiza a obra às suas expensas</b> e é remunerado <b>posteriormente pela exploração do serviço decorrente da obra</b>.</p><p class='fb-fonte'>Resumo 09 · <i>Concessão Comum</i></p>",
39:"<p>Errado — a descrição é da <b>concessão precedida de obra</b>. No resumo: <b>na Concessão Precedida de Obra, o particular deve realizar a obra às suas expensas e será remunerado posteriormente pela exploração do serviço decorrente da obra</b>.</p><p>Na <b>Concessão Simples</b>, ao contrário, <b>o particular delegatário é remunerado apenas pelas tarifas pagas pelos usuários</b> — é essa frase que o quadro comparativo usa para opor a concessão comum à concessão especial.</p><p class='fb-fonte'>Resumo 09 · <i>Concessão Comum</i></p>",
40:"<p>Certo nas três informações. O resumo abre a seção dizendo que as concessões especiais <b>são as Parcerias Público-Privadas (PPP)</b>, que <b>submete-se à lei 11.079/04</b> e que <b>a concessão especial pode ser patrocinada ou administrativa</b>.</p><p>Fixe a divisão pela fonte do dinheiro: <b>patrocinada</b> = <b>contraprestação do Estado + tarifa do usuário</b>; <b>administrativa</b> = <b>remuneração integral do Estado</b>, sendo a Administração <b>usuária direta ou indireta</b>.</p><p class='fb-fonte'>Resumo 09 · <i>Concessão Especial</i></p>",
41:"<p>Errado: a assertiva trocou as duas espécies. No resumo, <b>Concessão Patrocinada: contraprestação do Estado + tarifa do usuário</b>; <b>Concessão Administrativa: remuneração integral do Estado</b>, hipótese em que <b>a administração Pública é usuária direta ou indireta</b>.</p><p>O elemento comum às duas é o que define a PPP: <b>sempre haverá uma contraprestação pecuniária do Poder Público ao parceiro privado</b>.</p><p class='fb-fonte'>Resumo 09 · <i>Concessão Especial</i></p>",
42:"<p>Certo, é o fecho da seção de concessão especial: <b>se o contrato não prevê essa contraprestação pecuniária, não será PPP, e sim concessão comum</b>.</p><p>É exatamente a segunda <b>QUESTÃO-PEGADINHA</b> do resumo (CESPE — CODEVASF 2021), dada como <b>ERRADA</b>: se não envolve contraprestação pecuniária do parceiro público, <b>não temos uma parceria (concessão especial), e sim uma concessão comum, onde a contraprestação pecuniária é realizada por meio de tarifas pagas pelos usuários dos serviços</b>.</p><p class='fb-fonte'>Resumo 09 · <i>Concessão Especial / questão-pegadinha CODEVASF 2021</i></p>",
43:"<p>Errado. É a primeira <b>QUESTÃO-PEGADINHA</b> do resumo (CESPE — IPHAN 2018), com gabarito <b>ERRADO</b>, e o comentário dele é de uma linha: <b>são os governos estaduais e municipais que concentram a maior parte das PPP</b>.</p><p>Guarde em par com a outra pegadinha da mesma página: não existe PPP <b>sem contraprestação pecuniária do parceiro público</b> — sem ela, é <b>concessão comum</b>.</p><p class='fb-fonte'>Resumo 09 · <i>Concessão Especial — questão-pegadinha IPHAN 2018</i></p>",
44:"<p>Certo nos dois regimes, conforme o <b>Tome Nota 11</b>: na <b>Concessão Comum (Lei 8.987/95)</b>, <b>a lei não estabelece prazo máximo para a vigência dos contratos de concessão de serviços públicos</b>; na <b>Concessão Especial — PPP (Lei 11.079/04)</b>, <b>a lei estabelece prazo mínimo de 5 e máximo de 35 anos (incluindo eventual prorrogação)</b>.</p><p>Não confunda \"sem prazo máximo legal\" com \"prazo indeterminado\": o conceito de concessão exige <b>prazo determinado</b> no contrato.</p><p class='fb-fonte'>Resumo 09 · <i>Conceitos Importantes — Tome Nota 11</i></p>",
45:"<p>Certo pela letra do <b>Tome Nota 15</b>: <b>reversão é a transferência ao poder concedente (U, E, DF, M) dos bens do concessionário, afetados ao serviço público e necessários à sua continuidade, ao término do contrato de concessão</b>.</p><p>O resumo completa em dois passos. <b>Tome Nota 16:</b> extinta a concessão, <b>retornam ao poder concedente todos os bens reversíveis, direitos e privilégios transferidos ao concessionário</b>, conforme o edital e o contrato. <b>Tome Nota 17:</b> no <b>advento do termo contratual</b>, a reversão far-se-á com a <b>indenização das parcelas dos investimentos vinculados a bens reversíveis ainda não amortizados ou depreciados</b>; mas, se o bem <b>não era exigido contratualmente nem fora utilizado</b> na prestação do serviço, <b>não há ressarcimento</b>.</p><p class='fb-fonte'>Resumo 09 · <i>Conceitos Importantes — Tome Nota 15</i></p>",
46:"<p>Certo, é o <b>Tome Nota 01</b>, inteiro: <b>não se caracteriza como descontinuidade do serviço a sua interrupção em situação de emergência, ou após prévio aviso: quando motivada por razões de ordem técnica ou de segurança das instalações; quando por inadimplemento do usuário, considerado o interesse da coletividade</b>.</p><p>Repare na arquitetura da regra: a <b>emergência</b> dispensa o aviso; as outras duas hipóteses exigem <b>prévio aviso</b>. E a ressalva final — <b>considerado o interesse da coletividade</b> — é a que sustenta o REsp 1.755.345, em que o corte de energia de <b>hospital municipal</b> inadimplente foi considerado errado.</p><p class='fb-fonte'>Resumo 09 · <i>Conceitos Importantes — Tome Nota 01</i></p>",
47:"<p>Errado, e o resumo já avisa entre colchetes. O <b>Tome Nota 04</b>: <b>a transferência de concessão ou de controle societário da concessionária sem a prévia anuência do poder concedente implicará a caducidade [não é anulação] da concessão</b>.</p><p>Faz sentido com a lógica do instituto: a caducidade é a extinção por <b>falta do concessionário</b>, e transferir a concessão sem autorização é justamente descumprir obrigação contratual. A <b>anulação</b> pressupõe <b>vício de legalidade</b> na própria concessão.</p><p class='fb-fonte'>Resumo 09 · <i>Conceitos Importantes — Tome Nota 04</i></p>",
48:"<p>Certo. O <b>Tome Nota 06</b> traz a <b>Súmula Vinculante 41 do STF</b>: <b>o serviço de iluminação pública não pode ser remunerado mediante taxa</b>. E o <b>Tome Nota 07</b> dá o fundamento: a caracterização desse serviço como <b>UNIVERSAL</b>, já que as taxas somente podem ser instituídas <b>em razão do exercício do poder de polícia</b> ou <b>pela utilização, efetiva ou potencial, de serviços públicos específicos e divisíveis</b>.</p><p>Encaixa com a classificação: a <b>iluminação pública</b> é serviço <b>uti universi</b>, de destinatários indeterminados — logo, não é <b>específico e divisível</b> e não admite taxa.</p><p class='fb-fonte off'>Não consta do Resumo 09 — o material reproduz as duas hipóteses de instituição de taxas, mas não indica o dispositivo; a referência ao art. 145, II, da CF vem de fora do resumo.</p>",
49:"<p>Errado por uma palavra invertida. O <b>Tome Nota 08</b> transcreve a súmula em sentido oposto: <b>STJ, Súmula 407 — é legítima a cobrança da tarifa de água fixada de acordo com as categorias de usuários e as faixas de consumo</b>.</p><p>Essa súmula conversa diretamente com a observação 04 da política tarifária: <b>as tarifas poderão ser diferenciadas em função das características técnicas e dos custos específicos provenientes do atendimento aos distintos segmentos de usuários</b>.</p><p class='fb-fonte'>Resumo 09 · <i>Conceitos Importantes — Tome Nota 08</i></p>",
50:"<p>Errado. Não há vedação: o <b>Tome Nota 13</b> diz exatamente o contrário — <b>é admitida a subconcessão, nos termos previstos no contrato de concessão, desde que expressamente autorizada pelo poder concedente</b>.</p><p>São <b>duas</b> condições cumulativas — previsão <b>no contrato</b> e <b>autorização expressa</b> do poder concedente. Ao lado dela, o <b>Tome Nota 02</b> permite que a concessionária contrate com terceiros atividades <b>inerentes, acessórias ou complementares</b> ao serviço concedido; e o <b>Tome Nota 04</b> pune com <b>caducidade</b> a transferência feita <b>sem prévia anuência</b>.</p><p class='fb-fonte'>Resumo 09 · <i>Conceitos Importantes — Tome Nota 13</i></p>",
51:"<p>Errado na ressalva. O <b>Tome Nota 18</b> traz a <b>ADC 57 do STF (03/10/2019)</b> sem exceção alguma: <b>concessionárias de serviços públicos podem terceirizar quaisquer de suas atividades, inclusive suas atividades-fim</b>.</p><p>A assertiva inverteu o \"inclusive\" em \"exceto\". Some a isso o <b>Tome Nota 14</b>, que mantém a responsabilidade no lugar: incumbe à concessionária a execução do serviço, <b>respondendo por todos os prejuízos causados ao poder concedente, aos usuários ou a terceiros, sem que a fiscalização exercida pelo órgão competente exclua ou atenue essa responsabilidade</b>.</p><p class='fb-fonte'>Resumo 09 · <i>Conceitos Importantes — Tome Nota 18</i></p>"
};

var PROVA_POOL=[];
for(var k in EX){ if(EX[k].t!=="match") PROVA_POOL.push(k); }

return {n:"09", nome:"Serviços públicos e concessões", pronto:true,
        CARDS:CARDS, QS:QS, FEY:{}, TEORIA:TEORIA, EX:EX, KIT:{}, UNITS:UNITS, COM:COM,
        DISCURSIVA:"", CASO:"", TEC:TEC, TECNOTA:TECNOTA, PROVA_POOL:PROVA_POOL};
})();
